### ISSUE TITLE
Issue with bitsandbytes : CUDA Setup failed despite GPU being available.

### ISSUE THREAD

**Issue by VandeveldePaul** [huggingface/autotrain-advanced#149]
Hello,

I have an issue with bitsandbytes when i install the new version of autotrain-advanced (0.6.0)

Before installing it, I install bitsandbytes, torch and scipy and it works well:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!

But after installing autotrain-advanced with: pip install -U autotrain-advanced:

(autotrain-env) ➜  Falcon python3 -m bitsandbytes          
False

===================================BUG REPORT===================================
/home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('local/buinno'), PosixPath('@/tmp/.ICE-unix/3013,unix/buinno')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/457946bd_8f69_4f73_8bc0_23e84f7cb95c')}
The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('0')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

And when i try to do : autotrain setup --update-torch, I now get an error : ModuleNotFoundError: No module named '_lzma'

Do you have any idea to fix this problem ? 

Thank you

**Comment by VandeveldePaul** [comment]
I did these commands and it finally worked:

export BNB_CUDA_VERSION=122
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user/.local/cuda122
