### ISSUE TITLE
Running !pip install autotrain-advanced gives error on Colab

### ISSUE THREAD

**Issue by TanmayDoesAI** [huggingface/autotrain-advanced#158]
While running '!pip install autotrain-advanced' on google colab, it seems to give the following in the end after everything else is installed but this does not seem to interrupt the kernel.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.27.1, but you have requests 2.31.0 which is incompatible.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 1.13.1 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 1.13.1 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 1.13.1 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 1.13.1 which is incompatible.
Successfully installed Levenshtein-0.21.1 Pillow-8.2.0 accelerate-0.21.0 aiofiles-23.1.0 albumentations-1.3.0 arrow-1.2.3 autotrain-advanced-0.6.2 bitsandbytes-0.41.0 codecarbon-2.2.3 datasets-2.13.1 diffusers-0.18.2 dill-0.3.6 einops-0.6.1 evaluate-0.3.0 fastapi-0.100.0 ffmpy-0.3.1 fuzzywuzzy-0.18.0 gradio-3.37.0 gradio-client-0.2.10 h11-0.14.0 httpcore-0.17.3 httpx-0.24.1 huggingface-hub-0.16.4 imageio-2.9.0 ipadic-1.0.0 jiwer-2.2.0 joblib-1.2.0 linkify-it-py-2.0.2 loguru-0.7.0 markdown-it-py-2.2.0 mdit-py-plugins-0.3.3 multiprocess-0.70.14 nltk-3.5 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 orjson-3.9.2 peft-0.4.0 protobuf-4.23.4 pydub-0.25.1 pynvml-11.5.0 python-Levenshtein-0.21.1 python-multipart-0.0.6 rapidfuzz-3.1.2 requests-2.31.0 responses-0.18.0 sacremoses-0.0.53 safetensors-0.3.1 semantic-version-2.10.0 sentencepiece-0.1.99 starlette-0.27.0 tiktoken-0.4.0 tokenizers-0.13.3 torch-1.13.1 tqdm-4.62.1 transformers-4.31.0 triton-2.0.0.post1 trl-0.4.7 uc-micro-py-1.0.2 uvicorn-0.23.1 websockets-11.0.3 xxhash-3.2.0

WARNING: The following packages were previously imported in this runtime:
  [PIL]
You must restart the runtime in order to use newly installed versions.
```

here is the link for the entire output of installing [Output](https://gist.github.com/TanmayDoesAI/d12bb0e52435430a88504eb4d1f1e324)

**Comment by abhishekkrthakur** [comment]
you can ignore that error and it will still work.

**Comment by TanmayDoesAI** [comment]
Okay, thank you!

**Comment by saurabhbidwai** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible. Is this related?

@abhishekkrthakur same stands for this error if yes then I'm getting below error

> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 110, in train
    utils.enable_xformers(unet, config)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/utils.py", line 315, in enable_xformers
    unet.enable_xformers_memory_efficient_attention()
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 287, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 203, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU 

FYI, I have updated below parameters 
learning_rate = 5e-06 
num_steps = 300

**Comment by abhishekkrthakur** [comment]
you need to use a gpu machine

**Comment by saurabhbidwai** [comment]
its T4 GPU only on Colab

**Comment by abhishekkrthakur** [comment]
then a restart of the environment should fix it

**Comment by saurabhbidwai** [comment]
tried this multiple times
