### ISSUE TITLE
Run on CPU

### ISSUE THREAD

**Issue by apcameron** [huggingface/autotrain-advanced#160]
Is it possible to run this without a GPU locally?
If so what options need to be used as it does not work when It try it.

autotrain llm --train --project_name my-llm --model abhishek/llama-2-7b-hf-small-shards --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 2 --num_train_epochs 3 --trainer sft 
/media/Recorded_TV/Downloads/autotrain/env/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/media/Recorded_TV/Downloads/autotrain/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
2023-07-25 13:10:55.406 | INFO     | autotrain.cli.run_llm:run:446 - Running LLM
2023-07-25 13:10:55.406 | INFO     | autotrain.cli.run_llm:run:447 - Train: True
2023-07-25 13:10:55.406 | INFO     | autotrain.trainers.clm:train:38 - loading dataset from csv
Traceback (most recent call last):
  File "/media/Recorded_TV/Downloads/autotrain/env/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/media/Recorded_TV/Downloads/autotrain/env/lib/python3.10/site-packages/autotrain/cli/autotrain.py", line 34, in main
    command.run()
  File "/media/Recorded_TV/Downloads/autotrain/env/lib/python3.10/site-packages/autotrain/cli/run_llm.py", line 489, in run
    train_llm(params)
  File "/media/Recorded_TV/Downloads/autotrain/env/lib/python3.10/site-packages/autotrain/trainers/clm.py", line 105, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/media/Recorded_TV/Downloads/autotrain/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/media/Recorded_TV/Downloads/autotrain/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2281, in from_pretrained
    raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes`

**Comment by apcameron** [comment]
Yes it does
accelerate                0.21.0

**Comment by AR-javis** [comment]
The error message says that 8-bit quantization support isn't available as it was compiled without GPU support, suggesting that quantization is only available for GPUs for now.
