### ISSUE TITLE
SDXL does not appear to have a file named diffusion_pytorch_model.bin.

### ISSUE THREAD

**Issue by dx777** [huggingface/autotrain-advanced#170]
`autotrain dreambooth --model stabilityai/stable-diffusion-xl-base-1.0 --output /workspace/SDXL/output/ --image-path /workspace/SDXL/images/ --prompt "sks dog" --resolution 1024 --batch-size 1 --num-steps 350 --fp16 --gradient-accumulation 1 --lr 1e-4 --use-8bit-adam`

Results in:

```
> INFO    Running DreamBooth Training
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Downloading (…)ch_model.safetensors:   0%|                                                                                 | 10.5M/10.3G [00:08<2:18:23, 1.24MB/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/43d0fa61587d4b14f40964aca23b7c4c701edcee/unet/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/hub_utils.py", line 311, in _get_model_file
    model_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64c24716-5df1da1d54d411b35ac77448;138dcdd1-7f3c-431a-988f-a1e587f608be)

Entry Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/43d0fa61587d4b14f40964aca23b7c4c701edcee/unet/diffusion_pytorch_model.bin.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 36, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_dreambooth.py", line 418, in run
    train_dreambooth(params)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/main.py", line 82, in train
    tokenizers, text_encoders, vae, unet, noise_scheduler = utils.load_model_components(
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/utils.py", line 268, in load_model_components
    unet = UNet2DConditionModel.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 576, in from_pretrained
    model_file = _get_model_file(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/hub_utils.py", line 340, in _get_model_file
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-xl-base-1.0 does not appear to have a file named diffusion_pytorch_model.bin.
```

**Comment by abhishekkrthakur** [comment]
it seems like it didn't download properly on your machine.
could you try to clear your cache and try again?
by default huggingface cache is located at `~/.cache/huggingface/`

**Comment by dx777** [comment]
> it seems like it didn't download properly on your machine. could you try to clear your cache and try again? by default huggingface cache is located at `~/.cache/huggingface/`

Thanks for the fast response. Removing the cache worked 👍
