### ISSUE TITLE
Requirements : Pillow version issue

### ISSUE THREAD

**Issue by UTpH** [huggingface/autotrain-advanced#171]
The requirements.txt has Pillow==8.2.0 which doesn't install. 
Using the latest version of Pillow works (removing the version for Pillow from requirements.txt)
On mac M2

**Comment by SeaJungg** [comment]
simillar issue here:
(on wsl2 + python 3.10)

```
...
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [175 lines of output]
...
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-byh8sq7o/pillow_e7797c02dd99496892c47d1c63203378/setup.py", line 976, in <module>
          setup(
        File "/home/nexusai/2023/7/tuning/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/nexusai/2023/7/tuning/.venv/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 346, in run
          self.run_command("build")
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/nexusai/2023/7/tuning/.venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-install-byh8sq7o/pillow_e7797c02dd99496892c47d1c63203378/setup.py", line 788, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-byh8sq7o/pillow_e7797c02dd99496892c47d1c63203378/setup.py", line 1033, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
ERROR: Could not build wheels for Pillow, which is required to install pyproject.toml-based projects
```

**Comment by jonasr87** [comment]
Had the same problem. Solved it by running:
sudo apt-get install -y libjpeg8-dev zlib1g-dev libtiff5-dev libfreetype6-dev liblcms2-dev libopenjp2-7-dev libwebp-dev

Then it worked to install Pillow. I also ran "pip install git+https://github.com/huggingface/autotrain-advanced.git" to make sure to get the latest version.

**Comment by viktors1982** [comment]
> Had the same problem. Solved it by running: sudo apt-get install -y libjpeg8-dev zlib1g-dev libtiff5-dev libfreetype6-dev liblcms2-dev libopenjp2-7-dev libwebp-dev
> 
> Then it worked to install Pillow. I also ran "pip install git+https://github.com/huggingface/autotrain-advanced.git" to make sure to get the latest version.

it helped me, thank you - wsl ubuntu

**Comment by mortenfj** [comment]
I was using python 3.10.
I fixed this by installing:
apt-get install -y libjpeg-dev
apt-get install -y python3-dev

That made it so the compilation of pillow from source would run without issues.
Hope this helps someone.
