### ISSUE TITLE
resume_from_checkpoint throws error in the LoraLoaderMixin.load_lora_into_unet() method

### ISSUE THREAD

**Issue by cohan8999** [huggingface/autotrain-advanced#183]
I am able to train just fine, but resuming from checkpoints doesn't seem to work.

I'm running Ubuntu 22.04 on WSL with Cuda 11.8 and the latest Pytorch.

I've tried to train a 2nd model and set a low checkpointing-steps just to test, and I got the same error when trying to resume training.

Here's my console output:

```
autotrain dreambooth --num-steps 5000 --resume-from-checkpoint Output/NatureXL/checkpoint-5000 --checkpointing-steps 2500 --model stabilityai/stable-diffusion-xl-base-1.0 --use-8bit-adam --xformers --output Output/NatureXL --image-path training/Input/ --prompt "in the style of NatureXL" --resolution 1024 --batch-size 1 --fp16 --gradient-accumulation 4 --lr 1e-4
> INFO    Namespace(version=False, model='stabilityai/stable-diffusion-xl-base-1.0', revision=None, tokenizer=None, image_path='training/Input/', class_image_path=None, prompt='in the style of NatureXL', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, output='Output/NatureXL', seed=42, resolution=1024, center_crop=None, train_text_encoder=None, batch_size=1, sample_batch_size=4, epochs=1, num_steps=5000, checkpointing_steps=2500, resume_from_checkpoint='Output/NatureXL/checkpoint-5000', gradient_accumulation=4, gradient_checkpointing=None, lr=0.0001, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=True, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=True, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, hub_token=None, hub_model_id=None, push_to_hub=None, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, func=<function run_dreambooth_command_factory at 0x7f8456f577f0>)
> INFO    Running DreamBooth Training
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'dynamic_thresholding_ratio', 'clip_sample_range', 'variance_type', 'thresholding'} was not found in config. Values will be initialized to default values.
> INFO    Computing text embeddings for prompt: in the style of NatureXL
> INFO    ***** Running training *****
> INFO      Num examples = 13762
> INFO      Num batches each epoch = 13762
> INFO      Num Epochs = 2
> INFO      Instantaneous batch size per device = 1
> INFO      Total train batch size (w. parallel, distributed & accumulation) = 4
> INFO      Gradient Accumulation steps = 4
> INFO      Total optimization steps = 5000
> INFO      Training config = model='stabilityai/stable-diffusion-xl-base-1.0' revision=None tokenizer=None image_path='training/Input/' class_image_path=None prompt='in the style of NatureXL' class_prompt=None num_class_images=100 class_labels_conditioning=None prior_preservation=False prior_loss_weight=1.0 output='Output/NatureXL' seed=42 resolution=1024 center_crop=False train_text_encoder=False batch_size=1 sample_batch_size=4 epochs=2 num_steps=5000 checkpointing_steps=2500 resume_from_checkpoint='Output/NatureXL/checkpoint-5000' gradient_accumulation=4 gradient_checkpointing=False lr=0.0001 scale_lr=False scheduler='constant' warmup_steps=0 num_cycles=1 lr_power=1.0 dataloader_num_workers=0 use_8bit_adam=True adam_beta1=0.9 adam_beta2=0.999 adam_weight_decay=0.01 adam_epsilon=1e-08 max_grad_norm=1.0 allow_tf32=False prior_generation_precision=None local_rank=-1 xformers=True pre_compute_text_embeddings=False tokenizer_max_length=None text_encoder_use_attention_mask=False rank=4 xl=True fp16=True bf16=False hub_token=None hub_model_id=None push_to_hub=False validation_prompt=None num_validation_images=4 validation_epochs=50 checkpoints_total_limit=None validation_images=None logging=False
Resuming from checkpoint checkpoint-5000
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 36, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_dreambooth.py", line 469, in run
    train_dreambooth(params)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/main.py", line 233, in train
    trainer = Trainer(
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 130, in __init__
    self._resume_from_checkpoint()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 203, in _resume_from_checkpoint
    self.accelerator.load_state(os.path.join(self.config.output, path))
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 2695, in load_state
    hook(models, input_dir)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/main.py", line 177, in load_model_hook
    LoraLoaderMixin.load_lora_into_unet(lora_state_dict, network_alpha=network_alpha, unet=unet_)
TypeError: LoraLoaderMixin.load_lora_into_unet() got an unexpected keyword argument 'network_alpha'
```

**Comment by loboere** [comment]
same error, please authors answer this error
