### ISSUE TITLE
setup fails to install dreambooth

### ISSUE THREAD

**Issue by loranger** [huggingface/autotrain-advanced#185]
Hi,

I try to run autotrain-advanced on my macbook pro m1 max, but it seems it misses some dependencies:

I ran setup

```shell
❯ autotrain setup
/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
> WARNING ❌ Some DreamBooth components are missing! Please run `autotrain setup` to install it. Ignore this warning if you are not using DreamBooth or running `autotrain setup` already.
> INFO    Installing latest transformers@main
> INFO    Successfully installed latest transformers
> INFO    Installing latest peft@main
> INFO    Successfully installed latest peft
> INFO    Installing latest diffusers@main
> INFO    Successfully installed latest diffusers
> INFO    Installing latest trl@main
> INFO    Successfully installed latest trl
```

But every time I run autotrain, it complains some dreambooth components still misses:

```shell
❯ autotrain dreambooth --model ../Models/sd_xl_base_1.0.safetensors --output ../Models/ --image-path Laurent/birme-512x512 --prompt "photo of a man" --resolution 1024 --batch-size 1 --num-steps 500 --fp16 --gradient-accumulation 4 --lr 1e-4
/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
> WARNING ❌ Some DreamBooth components are missing! Please run `autotrain setup` to install it. Ignore this warning if you are not using DreamBooth or running `autotrain setup` already.
> INFO    Namespace(version=False, model='../Models/sd_xl_base_1.0.safetensors', revision=None, tokenizer=None, image_path='Laurent/birme-512x512', class_image_path=None, prompt='photo of a man', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, output='../Models/', seed=42, resolution=1024, center_crop=None, train_text_encoder=None, batch_size=1, sample_batch_size=4, epochs=1, num_steps=500, checkpointing_steps=100000, resume_from_checkpoint=None, gradient_accumulation=4, gradient_checkpointing=None, lr=0.0001, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=None, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=None, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, hub_token=None, hub_model_id=None, push_to_hub=None, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, func=<function run_dreambooth_command_factory at 0x10f965a80>)
Traceback (most recent call last):
  File "/opt/homebrew/bin/autotrain", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/autotrain/cli/autotrain.py", line 35, in main
    command = args.func(args)
              ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/autotrain/cli/run_dreambooth.py", line 28, in run_dreambooth_command_factory
    return RunAutoTrainDreamboothCommand(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/autotrain/cli/run_dreambooth.py", line 455, in __init__
    num_images = count_images(self.args.image_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/autotrain/cli/run_dreambooth.py", line 22, in count_images
    for files in VALID_IMAGE_EXTENSIONS:
                 ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'VALID_IMAGE_EXTENSIONS' is not defined
```

Can you help, please ?

**Comment by lustfeind** [comment]
Same here. Macbook m1 pro.

**Comment by indievish** [comment]
`pip install torchvision` before running `autotrainer setup`

**Comment by IvoPereira** [comment]
I am facing exactly the same issue, and this doesn't help.


> `pip install torchvision` before running `autotrainer setup`

**Comment by lustfeind** [comment]
> `pip install torchvision` before running `autotrainer setup`

Not working anyway,.. 
Btw. I would apreciate a lot a tutorial or step by step doc for installing and running it on apple silicon. It would be great, because Abhishek seems to use it on his MacBook too.
