### ISSUE TITLE
Expected scalar type Float but found Half

### ISSUE THREAD

**Issue by darshil-vt** [huggingface/autotrain-advanced#191]
autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path . --use_peft --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft 

Getting this error:

RuntimeError: expected scalar type Float but found Half

**Comment by abhishekkrthakur** [comment]
please run `autotrain setup`

**Comment by darshil-vt** [comment]
I tried running `autotrain setup` but I'm getting this error now.

ValueError: `do_sample` is set to `False`. However, temperature is set to 0.9 -- this flag is only used in sample-based generation modes. Set `do_sample=True` or unset temperature to continue.

**Comment by abhishekkrthakur** [comment]
@darshil-vt are you using `--inference` flag?

**Comment by darshil-vt** [comment]
@abhishekkrthakur No. I am not using `--inference` flag

I am using this:

autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path . --use_peft --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft

**Comment by darshil-vt** [comment]
I unistalled autotrain-advanced and tried it and installed autotrain-advanced in whole new system and again tried it but i am getting this same error:

ValueError: `do_sample` is set to `False`. However, temperature is set to 0.9 -- this flag is only used in sample-based generation modes. Set `do_sample=True` or unset temperature to continue.

And this is the whole terminal I'm getting:

2023-08-09 09:19:36.354 | WARNING  | autotrain.cli.run_dreambooth:<module>:15 - ❌ Some DreamBooth components are missing! Please run `autotrain setup` to install it. Ignore this warning if you are not using DreamBooth or running `autotrain setup` already.
2023-08-09 09:19:37.271 | INFO     | autotrain.cli.run_llm:run:364 - Running LLM
2023-08-09 09:19:37.271 | INFO     | autotrain.cli.run_llm:run:365 - Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='.', train_split='train', valid_split=None, text_column='text', model='meta-llama/Llama-2-7b-hf', learning_rate=0.0002, num_train_epochs=3, train_batch_size=12, eval_batch_size=4, warmup_ratio=0.1, gradient_accumulation_steps=1, optimizer='adamw_torch', scheduler='linear', weight_decay=0.0, max_grad_norm=1.0, seed=42, add_eos_token=False, block_size=-1, use_peft=True, lora_r=16, lora_alpha=32, lora_dropout=0.05, training_type='generic', train_on_inputs=False, logging_steps=-1, project_name='my-llm', evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, fp16=False, push_to_hub=False, use_int8=False, model_max_length=1024, repo_id=None, use_int4=False, trainer='sft', target_modules=None, func=<function run_llm_command_factory at 0x7f3e5a971990>)
2023-08-09 09:19:37.272 | INFO     | autotrain.trainers.clm:train:48 - loading dataset from csv
Using pad_token, but it is not set yet.
Downloading (…)lve/main/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 609/609 [00:00<00:00, 2.32MB/s]
Downloading (…)fetensors.index.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26.8k/26.8k [00:00<00:00, 59.9MB/s]
Downloading (…)of-00002.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.98G/9.98G [14:26<00:00, 11.5MB/s]
Downloading (…)of-00002.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.50G/3.50G [05:05<00:00, 11.5MB/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [19:32<00:00, 586.23s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.67s/it]
Downloading (…)neration_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 167/167 [00:00<00:00, 685kB/s]
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 36, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 409, in run
    train_llm(params)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 115, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2971, in from_pretrained
    model.generation_config = GenerationConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py", line 689, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py", line 722, in from_dict
    config = cls(**{**config_dict, **kwargs})
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py", line 316, in __init__
    self.validate()
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py", line 354, in validate
    raise ValueError(
ValueError: `do_sample` is set to `False`. However, temperature is set to 0.9 -- this flag is only used in sample-based generation modes. Set `do_sample=True` or unset temperature to continue.

**Comment by abhishekkrthakur** [comment]
thank you for trying in a new environment. are you using any validation data?

**Comment by abhishekkrthakur** [comment]
i see that you are not. ill try to reproduce and come back to you.

**Comment by darshil-vt** [comment]
Okay, Thank you for the responses and I will be looking forward to your response.

**Comment by abhishekkrthakur** [comment]
okay. found the problem. it seems to be related to transformers. 
before running autotrain llm command, can you do: `pip install git+https://github.com/huggingface/transformers@v4.31-release`?
