### ISSUE TITLE
'You already created this model repo' issue with non-existing repos

### ISSUE THREAD

**Issue by Dbg-atlas** [huggingface/autotrain-advanced#206]
I ran autotrain with the following command:

`autotrain llm --train --project_name 'my-llm' --model meta-llama/Llama-2-7b-chat-hf --data_path db-atlas/fire_train --text_column text --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 10 --num_train_epochs 5 --trainer sft --push_to_hub --repo_id db-atlas/fire7b_0816`

The model finished training but it failed while pushing to hub, saying that the repo for the model already existed. This is an error, as no repo with that name existed prior to running the command. After pushing to huggingface fails, the repo has been created but there is only a .gitattributes file in it.

```
2023-08-16 09:57:36.426 | INFO     | autotrain.trainers.utils:merge_adapter:161 - Saving target model...
2023-08-16 09:57:36.505 | INFO     | autotrain.trainers.utils:merge_adapter:161 - Saving target model...
2023-08-16 09:57:36.693 | INFO     | autotrain.trainers.utils:merge_adapter:161 - Saving target model...
2023-08-16 09:57:36.718 | INFO     | autotrain.trainers.utils:merge_adapter:161 - Saving target model...
2023-08-16 09:57:49.732 | INFO     | __main__:train:315 - Pushing model to hub...
2023-08-16 09:57:50.156 | INFO     | __main__:train:315 - Pushing model to hub...
2023-08-16 09:57:50.199 | INFO     | __main__:train:315 - Pushing model to hub...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 325, in <module>
    train(config)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 317, in train
    api.create_repo(repo_id=config.repo_id, repo_type="model")
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 2308, in create_repo
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/create (Request ID: Root=1-64dc9d9e-4074d9e135352e28319225d1;50a7ec5f-cadb-4575-b41e-4bc4ade1ee47)

You already created this model repo
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 325, in <module>
    train(config)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 317, in train
    api.create_repo(repo_id=config.repo_id, repo_type="model")
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 2308, in create_repo
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/create (Request ID: Root=1-64dc9d9e-130414935b46c6d475762dd8;16c642ae-526f-4409-9dd8-10578b87b53a)

You already created this model repo
2023-08-16 09:57:50.810 | INFO     | __main__:train:315 - Pushing model to hub...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 325, in <module>
    train(config)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 317, in train
    api.create_repo(repo_id=config.repo_id, repo_type="model")
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 2308, in create_repo
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/create (Request ID: Root=1-64dc9d9e-60d659b1310a77ce2f0ee904;633a51c3-c837-46ba-9cfa-d183cdfde4f9)

You already created this model repo
```

**Comment by abhishekkrthakur** [comment]
huggingface hub was down for sometime. so might be related to that. your model should be available in `my-llm` folder. you can push it manually using git.

**Comment by Dbg-atlas** [comment]
> huggingface hub was down for sometime. so might be related to that. your model should be available in `my-llm` folder. you can push it manually using git.

I have done several tests in the last few days. The error I posted is from a test I did half an hour ago. Could the donw time still be the issue?

Anyway, I will try pushing manually, thanks.

**Comment by abhishekkrthakur** [comment]
half an hour ago was the downtime. if your username/repo is correct repo_id, it should always work :)

**Comment by abhishekkrthakur** [comment]
note that you need to login using a write token

**Comment by Dbg-atlas** [comment]
> half an hour ago was the downtime. if your username/repo is correct repo_id, it should always work :)

I had the same issues on Monday and Tuesday for several models I trained. I'm using a write token and I was able to push trained models a few weeks ago. It started failing this week.

**Comment by Dbg-atlas** [comment]
I got the same error with push_to_hub again, but pushing manually worked for me without any other changes.

**Comment by abhishekkrthakur** [comment]
i just tested it and it seems to work fine. i suggest you always update the autotrain before using as it is under very active development.
