### ISSUE TITLE
KeyError: 'text'

### ISSUE THREAD

**Issue by lianghsun** [huggingface/autotrain-advanced#226]
I tried to execute the following command,
```
autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path ./ --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft
```
but I keep getting a 'key error'.
```
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/autotrain/trainers/clm/__main__.py", line 297, in train
    trainer.train()
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/transformers/trainer.py", line 1815, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/accelerate/data_loader.py", line 556, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/accelerate/data_loader.py", line 519, in _fetch_batches
    batches.append(next(iterator))
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/trl/trainer/utils.py", line 464, in __iter__
    buffer.append(self.formatting_func(next(iterator)))
  File "/home/liang/miniconda3/envs/huggingface/lib/python3.10/site-packages/trl/trainer/utils.py", line 440, in <lambda>
    self.formatting_func = lambda x: x[dataset_text_field]
KeyError: 'text'
```
My dataset looks like below:
```
text, label
12345, 1
```

**Comment by abhishekkrthakur** [comment]
do you have any other csv or data files in `./` ?

**Comment by lianghsun** [comment]
Only this one.

**Comment by abhishekkrthakur** [comment]
is it named `train.csv` or something else? when using csvs the valid names are only train.csv and valid.csv if you dont specify the name explicitly using `--train-split` and `--valid-split`

**Comment by lianghsun** [comment]
Thank you for your response. Indeed, the issue was that I named the training set something other than `train.csv`. After renaming it, the training proceeded normally.

**Comment by Hadjerkhd** [comment]
I am having the same error, even in a did have a` train.csv `file that i did put in a directory called `data`, and I did specify the directory path using `--data_path`

**Comment by huvers** [comment]
Same as above.
