### ISSUE TITLE
"Error when initializing model" - Model shards failed to start

### ISSUE THREAD

**Issue by Dbg-atlas** [huggingface/autotrain-advanced#232]
I ran autotrain with the following command:

autotrain llm --train --project_name 'my-llm' --model meta-llama/Llama-2-13b-chat-hf --data_path db-atlas/fire_train --text_column text --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 18 --num_train_epochs 3 --trainer sft --push_to_hub --repo_id db-atlas/fire13b_0825 --merge_adapter

The model finished training way before the estimated runtime, just like explained in issue #212. As suggested in that solution I added `--merge_adapter` to my command. The model pushed to hub without problems and as far as I can tell it has the same structure and files as previously trained, fully working models.

My problem comes when initializing the model for inference, when the loading fails and returns error messages such as this:
```
2023-08-25T10:57:30.352453Z ERROR text_generation_launcher: Error when initializing model
2023-08-25T10:57:30.927965Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
RuntimeError: weight model.layers.0.self_attn.rotary_emb.inv_freq does not exist
2023-08-25T10:58:25.627712Z ERROR text_generation_launcher: Shard 0 failed to start 
```

Following those messages I noticed that one of the files generated during training "pytorch_model.bin.index.json", contained in previously trained models mentions to for example:

`"model.layers.0.self_attn.rotary_emb.inv_freq": "pytorch_model-00001-of-00003.bin",`

This is missing in the models I'm currently trying to train, for all layers. I don't know if I'm missing some step while training, as I followed the same procedure some days back with no errors.

**Comment by abhishekkrthakur** [comment]
could you please update transformers version and then try again? if you are using TGI, switch to the latest version.

**Comment by Dbg-atlas** [comment]
I tried again following your suggestions and got the same error. After that I started the training process from scratch with the following commands:

```
pip install autotrain-advanced
autotrain setup --update-torch

autotrain llm --train --project_name 'my-llm' --model meta-llama/Llama-2-13b-chat-hf --data_path db-atlas/fire_train --text_column text --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 18 --num_train_epochs 3 --trainer sft --push_to_hub --repo_id db-atlas/fire13b_0825 --merge_adapter
```
I am using TGI, but I'm already using the latest available version. The full error I'm getting is this:

```
2023-08-28T02:55:02.607405955-07:00 2023-08-28T09:55:02.607088Z  INFO text_generation_launcher: Args { model_id: " db-atlas/fire13b_0825", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "6474e648826f", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-28T02:55:02.608717046-07:00 2023-08-28T09:55:02.608606Z  INFO download: text_generation_launcher: Starting download process.
2023-08-28T02:55:05.568056463-07:00 2023-08-28T09:55:05.567766Z  INFO text_generation_launcher: Peft model detected.
2023-08-28T02:55:05.568091753-07:00 
2023-08-28T02:55:05.568095543-07:00 2023-08-28T09:55:05.567835Z  INFO text_generation_launcher: Loading the model it might take a while without feedback
2023-08-28T02:55:05.568099593-07:00 
2023-08-28T02:58:00.728586775-07:00 2023-08-28T09:58:00.728336Z  INFO text_generation_launcher: Loaded.
2023-08-28T02:58:00.728627235-07:00 
2023-08-28T02:58:00.728629465-07:00 2023-08-28T09:58:00.728389Z  INFO text_generation_launcher: Merging the lora weights.
2023-08-28T02:58:00.728630825-07:00 
2023-08-28T02:58:49.316117064-07:00 2023-08-28T09:58:49.315810Z  INFO text_generation_launcher: Saving the newly created merged model to  db-atlas/fire13b_0825
2023-08-28T02:58:49.316183964-07:00 
2023-08-28T02:59:06.328275419-07:00 Error: DownloadError
2023-08-28T02:59:06.328369168-07:00 2023-08-28T09:59:06.327995Z ERROR download: text_generation_launcher: Download encountered an error: 
Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]
Downloading shards:  33%|███▎      | 1/3 [00:42<01:25, 42.73s/it]
Downloading shards:  67%|██████▋   | 2/3 [01:25<00:42, 42.73s/it]
Downloading shards: 100%|██████████| 3/3 [01:53<00:00, 35.86s/it]
Downloading shards: 100%|██████████| 3/3 [01:53<00:00, 37.71s/it]
2023-08-28T02:59:06.328394648-07:00 
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:  33%|███▎      | 1/3 [00:04<00:08,  4.30s/it]
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:08<00:03,  3.95s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:10<00:00,  3.37s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:10<00:00,  3.56s/it]
2023-08-28T02:59:06.328399708-07:00 Traceback (most recent call last):
2023-08-28T02:59:06.328405038-07:00 
2023-08-28T02:59:06.328408438-07:00   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-08-28T02:59:06.328412638-07:00     sys.exit(app())
2023-08-28T02:59:06.328415818-07:00 
2023-08-28T02:59:06.328419268-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 127, in download_weights
2023-08-28T02:59:06.328422968-07:00     utils.download_and_unload_peft(model_id, revision, trust_remote_code=trust_remote_code)
2023-08-28T02:59:06.328427148-07:00 
2023-08-28T02:59:06.328429868-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/peft.py", line 41, in download_and_unload_peft
2023-08-28T02:59:06.328432808-07:00     model.save_pretrained(cache_dir, safe_serialization=True)
2023-08-28T02:59:06.328436118-07:00 
2023-08-28T02:59:06.328438928-07:00   File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1845, in save_pretrained
2023-08-28T02:59:06.328441958-07:00     safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
2023-08-28T02:59:06.328465897-07:00 
2023-08-28T02:59:06.328469757-07:00   File "/opt/conda/lib/python3.9/site-packages/safetensors/torch.py", line 282, in save_file
2023-08-28T02:59:06.328473027-07:00     serialize_file(_flatten(tensors), filename, metadata=metadata)
2023-08-28T02:59:06.328476497-07:00 
2023-08-28T02:59:06.328479417-07:00 safetensors_rust.SafetensorError: Error while serializing: IoError(Os { code: 28, kind: StorageFull, message: "No space left on device" })
2023-08-28T02:59:06.328483497-07:00 
2023-08-28T02:59:06.328486307-07:00 
2023-08-28T02:59:16.348667054-07:00 2023-08-28T09:59:16.348402Z  INFO text_generation_launcher: Args { model_id: "db-atlas/fire13b_0825", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "6474e648826f", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-28T02:59:16.348752263-07:00 2023-08-28T09:59:16.348639Z  INFO download: text_generation_launcher: Starting download process.
2023-08-28T02:59:18.910636653-07:00 2023-08-28T09:59:18.910409Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
2023-08-28T02:59:18.910685073-07:00 
2023-08-28T02:59:19.307062668-07:00 2023-08-28T09:59:19.306850Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-28T02:59:19.307473135-07:00 2023-08-28T09:59:19.307306Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-28T02:59:22.129166389-07:00 2023-08-28T09:59:22.128932Z ERROR text_generation_launcher: Error when initializing model
2023-08-28T02:59:22.129199019-07:00 Traceback (most recent call last):
2023-08-28T02:59:22.129202609-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 40, in __init__
2023-08-28T02:59:22.129205369-07:00     tokenizer = LlamaTokenizer.from_pretrained(
2023-08-28T02:59:22.129207799-07:00   File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
2023-08-28T02:59:22.129210579-07:00     raise EnvironmentError(
2023-08-28T02:59:22.129214229-07:00 OSError: Can't load tokenizer for ' db-atlas/fire13b_0825'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure ' db-atlas/fire13b_0825' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.
2023-08-28T02:59:22.129218099-07:00 
2023-08-28T02:59:22.129220259-07:00 During handling of the above exception, another exception occurred:
2023-08-28T02:59:22.129222679-07:00 
2023-08-28T02:59:22.129224749-07:00 Traceback (most recent call last):
2023-08-28T02:59:22.129226869-07:00   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-08-28T02:59:22.129229029-07:00     sys.exit(app())
2023-08-28T02:59:22.129231959-07:00   File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
2023-08-28T02:59:22.129234259-07:00     return get_command(self)(*args, **kwargs)
2023-08-28T02:59:22.129236689-07:00   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
2023-08-28T02:59:22.129238829-07:00     return self.main(*args, **kwargs)
2023-08-28T02:59:22.129240929-07:00   File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
2023-08-28T02:59:22.129260209-07:00     return _main(
2023-08-28T02:59:22.129262739-07:00   File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
2023-08-28T02:59:22.129264939-07:00     rv = self.invoke(ctx)
2023-08-28T02:59:22.129267019-07:00   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
2023-08-28T02:59:22.129269069-07:00     return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-08-28T02:59:22.129271279-07:00   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
2023-08-28T02:59:22.129273359-07:00     return ctx.invoke(self.callback, **ctx.params)
2023-08-28T02:59:22.129275419-07:00   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
2023-08-28T02:59:22.129277429-07:00     return __callback(*args, **kwargs)
2023-08-28T02:59:22.129279469-07:00   File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
2023-08-28T02:59:22.129281679-07:00     return callback(**use_params)  # type: ignore
2023-08-28T02:59:22.129284819-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
2023-08-28T02:59:22.129286979-07:00     server.serve(
2023-08-28T02:59:22.129289148-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
2023-08-28T02:59:22.129291668-07:00     asyncio.run(
2023-08-28T02:59:22.129293928-07:00   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-08-28T02:59:22.129296238-07:00     return loop.run_until_complete(main)
2023-08-28T02:59:22.129298378-07:00   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
2023-08-28T02:59:22.129300508-07:00     self.run_forever()
2023-08-28T02:59:22.129302578-07:00   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
2023-08-28T02:59:22.129304678-07:00     self._run_once()
2023-08-28T02:59:22.129307198-07:00   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
2023-08-28T02:59:22.129309278-07:00     handle._run()
2023-08-28T02:59:22.129313538-07:00   File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
2023-08-28T02:59:22.129315628-07:00     self._context.run(self._callback, *self._args)
2023-08-28T02:59:22.129317728-07:00 > File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
2023-08-28T02:59:22.129320128-07:00     model = get_model(
2023-08-28T02:59:22.129322258-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 187, in get_model
2023-08-28T02:59:22.129324388-07:00     return FlashLlama(
2023-08-28T02:59:22.129326478-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 48, in __init__
2023-08-28T02:59:22.129328528-07:00     tokenizer = AutoTokenizer.from_pretrained(
2023-08-28T02:59:22.129330598-07:00   File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 720, in from_pretrained
2023-08-28T02:59:22.129332608-07:00     return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2023-08-28T02:59:22.129334638-07:00   File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
2023-08-28T02:59:22.129336688-07:00     raise EnvironmentError(
2023-08-28T02:59:22.129338918-07:00 OSError: Can't load tokenizer for 'db-atlas/fire13b_0825'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'db-atlas/fire13b_0825' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
2023-08-28T02:59:22.129341138-07:00 
2023-08-28T02:59:22.612630580-07:00 2023-08-28T09:59:22.612369Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
2023-08-28T02:59:22.612667420-07:00 
2023-08-28T02:59:22.612671300-07:00 Traceback (most recent call last):
2023-08-28T02:59:22.612674470-07:00 
2023-08-28T02:59:22.612676700-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 40, in __init__
2023-08-28T02:59:22.612692280-07:00     tokenizer = LlamaTokenizer.from_pretrained(
2023-08-28T02:59:22.612694730-07:00 
2023-08-28T02:59:22.612697170-07:00   File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
2023-08-28T02:59:22.612699500-07:00     raise EnvironmentError(
2023-08-28T02:59:22.612702220-07:00 
2023-08-28T02:59:22.612704410-07:00 OSError: Can't load tokenizer for 'db-atlas/fire13b_0825'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'db-atlas/fire13b_0825' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.
2023-08-28T02:59:22.612707139-07:00 
2023-08-28T02:59:22.612709079-07:00 
2023-08-28T02:59:22.612711159-07:00 During handling of the above exception, another exception occurred:
2023-08-28T02:59:22.612713569-07:00 
2023-08-28T02:59:22.612716339-07:00 
2023-08-28T02:59:22.612718689-07:00 Traceback (most recent call last):
2023-08-28T02:59:22.612720869-07:00 
2023-08-28T02:59:22.612722829-07:00   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-08-28T02:59:22.612724899-07:00     sys.exit(app())
2023-08-28T02:59:22.612727259-07:00 
2023-08-28T02:59:22.612729189-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
2023-08-28T02:59:22.612731649-07:00     server.serve(
2023-08-28T02:59:22.612734119-07:00 
2023-08-28T02:59:22.612736239-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 195, in serve
2023-08-28T02:59:22.612738999-07:00     asyncio.run(
2023-08-28T02:59:22.612741329-07:00 
2023-08-28T02:59:22.612743379-07:00   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-08-28T02:59:22.612745499-07:00     return loop.run_until_complete(main)
2023-08-28T02:59:22.612747599-07:00 
2023-08-28T02:59:22.612749529-07:00   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
2023-08-28T02:59:22.612751729-07:00     return future.result()
2023-08-28T02:59:22.612753979-07:00 
2023-08-28T02:59:22.612755939-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 147, in serve_inner
2023-08-28T02:59:22.612761899-07:00     model = get_model(
2023-08-28T02:59:22.612764109-07:00 
2023-08-28T02:59:22.612766159-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 187, in get_model
2023-08-28T02:59:22.612768429-07:00     return FlashLlama(
2023-08-28T02:59:22.612770439-07:00 
2023-08-28T02:59:22.612772559-07:00   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 48, in __init__
2023-08-28T02:59:22.612774689-07:00     tokenizer = AutoTokenizer.from_pretrained(
2023-08-28T02:59:22.612776809-07:00 
2023-08-28T02:59:22.612780019-07:00   File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 720, in from_pretrained
2023-08-28T02:59:22.612782159-07:00     return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2023-08-28T02:59:22.612784269-07:00 
2023-08-28T02:59:22.612786219-07:00   File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
2023-08-28T02:59:22.612788329-07:00     raise EnvironmentError(
2023-08-28T02:59:22.612790449-07:00 
2023-08-28T02:59:22.612792539-07:00 OSError: Can't load tokenizer for 'db-atlas/fire13b_0825'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'db-atlas/fire13b_0825' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
2023-08-28T02:59:22.612795009-07:00  rank=0
2023-08-28T02:59:22.710589059-07:00 2023-08-28T09:59:22.710328Z ERROR text_generation_launcher: Shard 0 failed to start
2023-08-28T02:59:22.710616479-07:00 2023-08-28T09:59:22.710368Z  INFO text_generation_launcher: Shutting down shards
2023-08-28T02:59:22.710584179-07:00 Error: ShardCannotStart
```

**Comment by abhishekkrthakur** [comment]
whats the tgi command?

**Comment by Dbg-atlas** [comment]
I'm actually running the commands in a runpod pod, which is probably where the problem comes from. With previous models, the command worked in version 0.9.4 of TGI.

```
pod = runpod.create_pod(
    name="Project",
    image_name="ghcr.io/huggingface/text-generation-inference",
    gpu_type_id=gpu_type,
    cloud_type="SECURE",
    docker_args="--model-id db-atlas/fire13b_0825",
    gpu_count=gpu_count,
    volume_in_gb=volume,
    container_disk_in_gb=disk,
    ports=ports,
    volume_mount_path="/data",
)
```
But now just creating the pod will throw the error about not being able to load the shards.
