### ISSUE TITLE
ValueError: The model you want to train is loaded in 8-bit precision.

### ISSUE THREAD

**Issue by pritishmishra703** [huggingface/autotrain-advanced#234]
Ran into an error while fine-tuning LLAMA-2-7B. Details Below:

System Information:
1. OS: Ubuntu 22.04.3 LTS
2. CPU Memory: 125 GB+
3. GPU Memory: 25 GB

This is how I installed autotrain:

```
$ pip install autotrain-advanced
$ autotrain setup
```

Then I tried to run this command for fine-tuning LLAMA2:

```
$ autotrain llm 
--train --project_name '<<project_name>>' 
--model 'meta-llama/Llama-2-7b-hf'
--data_path '<<data_path>>' 
--text_column text 
--use_peft 
--learning_rate 2e-4 
--train_batch_size 2 
--num_train_epochs 3 
--trainer sft 
--fp16
```

Output:

```
> WARNING ❌ Some DreamBooth components are missing! Please run `autotrain setup` to install it. Ignore this warning if you are not using DreamBooth or running `autotrain setup` already.

> INFO    Running LLM

> INFO    Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='<<data_path>>', train_split='train', valid_split=None, text_column='text', model='meta-llama/Llama-2-7b-hf', learning_rate=0.0002, num_train_epochs=3, train_batch_size=2, warmup_ratio=0.1, gradient_accumulation_steps=1, optimizer='adamw_torch', scheduler='linear', weight_decay=0.0, max_grad_norm=1.0, seed=42, add_eos_token=False, block_size=-1, use_peft=True, lora_r=16, lora_alpha=32, lora_dropout=0.05, logging_steps=-1, project_name='<<project_name>>', evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, fp16=True, push_to_hub=False, use_int8=False, model_max_length=1024, repo_id=None, use_int4=False, trainer='sft', target_modules=None, merge_adapter=False, token=None, backend='default', username=None, func=<function run_llm_command_factory at 0x7fdcc05e6b90>)

Using pad_token, but it is not set yet.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.13s/it]

You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embedding dimension will be 32000. This might induce some performance reduction as *Tensor Cores* will not be available. For more details about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc

> INFO    creating trainer
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/home/pritish/FineTuneLLAMA2/env/lib/python3.10/site-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/home/pritish/FineTuneLLAMA2/env/lib/python3.10/site-packages/autotrain/trainers/clm/__main__.py", line 272, in train
    trainer = SFTTrainer(
  File "/home/pritish/FineTuneLLAMA2/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 212, in __init__
    super().__init__(
  File "/home/pritish/FineTuneLLAMA2/env/lib/python3.10/site-packages/transformers/trainer.py", line 407, in __init__
    raise ValueError(
ValueError: The model you want to train is loaded in 8-bit precision.  if you want to fine-tune an 8-bit model, please make sure that you have installed `bitsandbytes>=0.37.0`.
```

The error occurred while attempting to "create a trainer" after loading the model. I'm having trouble understanding the error due to two reasons:

## 1. I did not set my model to load in int8

As you can see in the above printed messages `use_int8` is clearly set to `False`.

## 2. bitsandbytes already installed

I already have bitsandbytes installed.

```
$ pip install bitesandbytes
Requirement already satisfied: bitsandbytes in ./env/lib/python3.10/site-packages (0.41.1)


$ python -m bitsandbytes
...
++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.6']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```

Please help me if I am doing something wrong.

**Comment by abhinand5** [comment]
I'm observing the same issue! Did you solve it? @pritishmishra703

**Comment by pritishmishra703** [comment]
Unfortunately not. I gave up on this eventually and made a training script myself. I recommend following this colab notebook: 
https://colab.research.google.com/drive/1PEQyJO1-f6j0S_XJ8DV50NkpzasXkrzd?usp=sharing

**Comment by pritishmishra703** [comment]
> I'm facing the same issue! Did you solve it? @pritishmishra703

Unfortunately not. I gave up on this eventually and made a training script myself. I recommend following this colab notebook:
https://colab.research.google.com/drive/1PEQyJO1-f6j0S_XJ8DV50NkpzasXkrzd?usp=sharing

**Comment by chukarsten** [comment]
We're also running into this.  Curiously enough, we see it on our CI runners but not running with pytest (for tests that are training models) on a remote machine.

**Comment by LydiaNyu** [comment]
I am facing this problem too, constantly.

**Comment by felipeary91** [comment]
Also found the same issue. Any workaround?

**Comment by abhishekkrthakur** [comment]
fixed.

**Comment by zhangxiangchn** [comment]
> fixed.

how to fixed? what should we do.

**Comment by mahmoudhage21** [comment]
I had the same error.
when you load the model, and set `quantization_config` to your bnb config file, I solved it by setting `load_in_4bit` in bnb config file to `True`

```
bnb_config = BitsAndBytesConfig(
    load_in_4bit =True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    use_safetensors=True, 
    quantization_config=bnb_config,
    trust_remote_code=True, 
    device_map= "auto",
)
tokenizer =AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
```

**Comment by ddofer** [comment]
Same issue (even when using vanilla BnB/Peft/Qlora/HF trainer, without autotrain. (With the ESM2 models)
Has anyone found the fix?
