### ISSUE TITLE
ModuleNotFoundError: No module named 'autotrain.autotrain'

### ISSUE THREAD

**Issue by Diego0511** [huggingface/autotrain-advanced#248]
I don't know somehow I got this error, can anyone help me with this? The exact error message is provided below:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/autotrain/__init__.py", line 22, in <module>
    from .autotrain import AutoTrain
ModuleNotFoundError: No module named 'autotrain.autotrain'

**Comment by AR-javis** [comment]
The logs suggest that you are using python 3.7. Autotrain is supported from python 3.8 onwards.
