### ISSUE TITLE
ImportError: cannot import name 'randn_tensor' from 'diffusers.utils'

### ISSUE THREAD

**Issue by amalgopal2015** [huggingface/autotrain-advanced#259]
Runtime error
tches).load()
  File "/app/env/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/app/env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/src/autotrain/cli/autotrain.py", line 8, in <module>
    from .run_llm import RunAutoTrainLLMCommand
  File "/app/src/autotrain/cli/run_llm.py", line 11, in <module>
    from autotrain.trainers.clm.__main__ import train as train_llm
  File "/app/src/autotrain/trainers/clm/__main__.py", line 23, in <module>
    from trl import SFTTrainer
  File "/app/env/lib/python3.9/site-packages/trl/__init__.py", line 7, in <module>
    from .extras import BestOfNSampler
  File "/app/env/lib/python3.9/site-packages/trl/extras/__init__.py", line 16, in <module>
    from .best_of_n_sampler import BestOfNSampler
  File "/app/env/lib/python3.9/site-packages/trl/extras/best_of_n_sampler.py", line 7, in <module>
    from ..models import SUPPORTED_ARCHITECTURES, PreTrainedModelWrapper
  File "/app/env/lib/python3.9/site-packages/trl/models/__init__.py", line 29, in <module>
    from .modeling_sd_base import (
  File "/app/env/lib/python3.9/site-packages/trl/models/modeling_sd_base.py", line 27, in <module>
    from diffusers.utils import randn_tensor
ImportError: cannot import name 'randn_tensor' from 'diffusers.utils' (/app/env/lib/python3.9/site-packages/diffusers/utils/__init__.py)
ERROR conda.cli.main_run:execute(47): `conda run /bin/bash -c autotrain setup && autotrain app --port 7860` failed. (See above for error)

**Comment by robss88** [comment]
i'm getting the same error started after the last commit by @abhishekkrthakur  

https://github.com/huggingface/autotrain-advanced/pull/222

**Comment by abhishekkrthakur** [comment]
which command causes this error?

**Comment by amalgopal2015** [comment]
> which command causes this error?

!autotrain dreambooth \
--model ${MODEL_NAME} \
--project-name ${PROJECT_NAME} \
--image-path images/ \
--prompt "${PROMPT}" \
--resolution ${RESOLUTION} \
--batch-size ${BATCH_SIZE} \
--num-steps ${NUM_STEPS} \
--gradient-accumulation ${GRADIENT_ACCUMULATION} \
--lr ${LEARNING_RATE} \
$( [[ "$USE_FP16" == "True" ]] && echo "--fp16" ) \
$( [[ "$USE_XFORMERS" == "True" ]] && echo "--xformers" ) \
$( [[ "$TRAIN_TEXT_ENCODER" == "True" ]] && echo "--train-text-encoder" ) \
$( [[ "$USE_8BIT_ADAM" == "True" ]] && echo "--use-8bit-adam" ) \
$( [[ "$GRADIENT_CHECKPOINTING" == "True" ]] && echo "--gradient-checkpointing" ) \
$( [[ "$PUSH_TO_HUB" == "True" ]] && echo "--push-to-hub --token ${HF_TOKEN} --repo-id ${REPO_ID}" )

**Comment by robss88** [comment]
ok it looks like it's working again now so far thank you!

**Comment by upperhouse** [comment]
Hi there. The same issue seems to be happening again:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.0.3 which is incompatible.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible.
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 8, in <module>
    from .run_llm import RunAutoTrainLLMCommand
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 11, in <module>
    from autotrain.trainers.clm.__main__ import train as train_llm
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 23, in <module>
    from trl import SFTTrainer
  File "/usr/local/lib/python3.10/dist-packages/trl/__init__.py", line 7, in <module>
    from .extras import BestOfNSampler
  File "/usr/local/lib/python3.10/dist-packages/trl/extras/__init__.py", line 16, in <module>
    from .best_of_n_sampler import BestOfNSampler
  File "/usr/local/lib/python3.10/dist-packages/trl/extras/best_of_n_sampler.py", line 7, in <module>
    from ..models import SUPPORTED_ARCHITECTURES, PreTrainedModelWrapper
  File "/usr/local/lib/python3.10/dist-packages/trl/models/__init__.py", line 29, in <module>
    from .modeling_sd_base import (
  File "/usr/local/lib/python3.10/dist-packages/trl/models/modeling_sd_base.py", line 27, in <module>
    from diffusers.utils import randn_tensor
ImportError: cannot import name 'randn_tensor' from 'diffusers.utils' (/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py)

**Comment by mmazurkevich** [comment]
@upperhouse New version of https://github.com/huggingface/diffusers/releases was released three hours ago. Try to dowangrade the version of the library, for me it's helped.
First, check which version of `diffusers` you have right now:
`pip show diffusers`
If it's 0.21.0, remove it and install the previous release
`pip uninstall diffusers`
`pip install diffusers==0.20.2`

**Comment by saurabhbidwai** [comment]
Same issue again, what should I do?

Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 8, in <module>
    from .run_llm import RunAutoTrainLLMCommand
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 11, in <module>
    from autotrain.trainers.clm.__main__ import train as train_llm
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 23, in <module>
    from trl import SFTTrainer
  File "/usr/local/lib/python3.10/dist-packages/trl/__init__.py", line 7, in <module>
    from .extras import BestOfNSampler
  File "/usr/local/lib/python3.10/dist-packages/trl/extras/__init__.py", line 16, in <module>
    from .best_of_n_sampler import BestOfNSampler
  File "/usr/local/lib/python3.10/dist-packages/trl/extras/best_of_n_sampler.py", line 7, in <module>
    from ..models import SUPPORTED_ARCHITECTURES, PreTrainedModelWrapper
  File "/usr/local/lib/python3.10/dist-packages/trl/models/__init__.py", line 29, in <module>
    from .modeling_sd_base import (
  File "/usr/local/lib/python3.10/dist-packages/trl/models/modeling_sd_base.py", line 27, in <module>
    from diffusers.utils import randn_tensor
ImportError: cannot import name 'randn_tensor' from 'diffusers.utils' (/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py)

**Comment by abhishekkrthakur** [comment]
please run autotrain setup or update trl to main branch manually

**Comment by qas2021** [comment]
Still faced this issue while finetuning using autotrain fixed it by changing dockerfile of training model huggingface space created by autotrain to:
FROM huggingface/autotrain-advanced:latest
RUN pip uninstall -y diffusers 
RUN pip install diffusers==0.20.2
CMD autotrain api --port 7860 --host 0.0.0.0
