### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/content/images/.ipynb_checkpoints'

### ISSUE THREAD

**Issue by saurabhbidwai** [huggingface/autotrain-advanced#264]
Steps:   0% 0/500 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py:1471: FutureWarning: `LoRAAttnProcessor2_0` is deprecated and will be removed in version 0.26.0. Make sure use AttnProcessor2_0 instead by settingLoRA layers to `self.{to_q,to_k,to_v,to_out[0]}.lora_layer` respectively. This will be done automatically when using `LoraLoaderMixin.load_lora_weights`
  deprecate(
Steps:   0% 0/500 [00:11<?, ?it/s, loss=0.115, lr=0.0001]> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 273, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 350, in train
    for step, batch in enumerate(self.train_dataloader):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 394, in __iter__
    next_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/datasets.py", line 167, in __getitem__
    instance_image = Image.open(self.instance_images_path[index % self.num_instance_images])
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/content/images/.ipynb_checkpoints'

**Comment by abhishekkrthakur** [comment]
as explained by the error, you have non image files in the image directory. remove them.

**Comment by saurabhbidwai** [comment]
Just .png files

![image](https://github.com/huggingface/autotrain-advanced/assets/22415674/2c80cffb-deb8-4229-a842-bee3c1a5bca4)

**Comment by abhishekkrthakur** [comment]
click on show hidden files. you have .ipynb_checkpoints too. if it doesnt work, delete the folder and create a new one.

**Comment by saurabhbidwai** [comment]
Thanks it was resolved.
