### ISSUE TITLE
Autotrainer advanced UI error while starting training

### ISSUE THREAD

**Issue by Stealthwriter** [huggingface/autotrain-advanced#270]
I get this error when starting training after adding a job, what is the issue?

![image](https://github.com/huggingface/autotrain-advanced/assets/126798556/11d16f16-de1b-4008-80fc-152ee7729b42)

**Comment by abhishekkrthakur** [comment]
clicking on logs will tell you more. note that this is a paid product and you will be charged, so it could be missing payment information!

**Comment by Stealthwriter** [comment]
> clicking on logs will tell you more. note that this is a paid product and you will be charged, so it could be missing payment information!

I'm getting this error in logs 
Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/app/env/lib/python3.9/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/app/env/lib/python3.9/site-packages/gradio/blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/app/env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/app/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/env/lib/python3.9/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/app/src/autotrain/apps/llm.py", line 42, in start_training
    ids = project.create()
  File "/app/src/autotrain/project.py", line 182, in create
    return self.create_spaces()
  File "/app/src/autotrain/project.py", line 171, in create_spaces
    space_id = sr.prepare()
  File "/app/src/autotrain/backend.py", line 252, in prepare
    space_id = self._create_space()
  File "/app/src/autotrain/backend.py", line 314, in _create_space
    api.create_repo(
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 2308, in create_repo
    hf_raise_for_status(r)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create (Request ID: Root=1-650847eb-089f13627195d1901bb69c14;c98e3bda-4d31-4057-b8a2-92487c8d4ef5)

user stealthwriter cannot upgrade to a100-large

**Comment by abhishekkrthakur** [comment]
please use a write token. 
if you need a100, contact website@hf.co for access.

**Comment by Stealthwriter** [comment]
is it possible to host it on my own server?

**Comment by abhishekkrthakur** [comment]
no. you can use the cli

**Comment by Stealthwriter** [comment]
Thanks for the response. Where can I find the documentation to run the trainer on my own gp using cli?

**Comment by abhishekkrthakur** [comment]
currently there is no documentation for cli. its in the works.
you can do `pip install autotrain-advanced` and then use the cli command `autotrain` to explore further.
im closing this issue since its deviating from the original topic. please feel free to open a new issue with specific problem that you are facing.
