### ISSUE TITLE
WARNING: Clicking Start Training will incur costs!

### ISSUE THREAD

**Issue by asherisaac** [huggingface/autotrain-advanced#274]
Anytime I click Start Training it gives this error no matter what I try.

WARNING: Clicking Start Training will incur costs!

**Comment by abhishekkrthakur** [comment]
what do you see in the logs? have you attached a valid payment method to your account?

**Comment by asherisaac** [comment]
Hi, here are the logs. Yes I have a valid payment method:

Train data: ['/tmp/gradio/cc4e15847efcfe7fe2fb3a30ccd0a1b0bd2b0b48/Autotrain Kids Book Test2 - Sheet1.csv']
Valid data: []
Column mapping: {'text': 'text'}

Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/app/env/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 2308, in create_repo
    hf_raise_for_status(r)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create (Request ID: Root=1-650c2a7a-07eb49971498931360b22b78;1e5a415e-d9db-4017-95d1-4b738321470a)

You don't have the rights to create a dataset under this namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/app/env/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/datasets/asherisaac/autotrain-data-xonj-hbfr-uuz9

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/app/env/lib/python3.9/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/app/env/lib/python3.9/site-packages/gradio/blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/app/env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/app/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/env/lib/python3.9/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/app/src/autotrain/apps/llm.py", line 40, in start_training
    dset.prepare()
  File "/app/src/autotrain/dataset.py", line 295, in prepare
    preprocessor.prepare()
  File "/app/src/autotrain/preprocessor/text.py", line 219, in prepare
    train_df.push_to_hub(
  File "/app/env/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 5422, in push_to_hub
    repo_id, split, uploaded_size, dataset_nbytes, repo_files, deleted_size = self._push_parquet_shards_to_hub(
  File "/app/env/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 5240, in _push_parquet_shards_to_hub
    api.create_repo(
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 2316, in create_repo
    self.repo_info(repo_id=repo_id, repo_type=repo_type, token=token)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1868, in repo_info
    return method(
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1741, in dataset_info
    hf_raise_for_status(r)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-650c2a7a-25d9caa216c2847d1c3d5102;99f5b9d2-b3a9-45fa-b61f-0edcdcd43e80)

Repository Not Found for url: https://huggingface.co/api/datasets/asherisaac/autotrain-data-xonj-hbfr-uuz9.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
> INFO    Dataset: xonj-hbfr-uuz9 (lm_training)
Train data: ['/tmp/gradio/cc4e15847efcfe7fe2fb3a30ccd0a1b0bd2b0b48/Autotrain Kids Book Test2 - Sheet1.csv']
Valid data: []
Column mapping: {'text': 'text'}

Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/app/env/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 2308, in create_repo
    hf_raise_for_status(r)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create (Request ID: Root=1-650c2a7c-26a468824231d61074f6698c;96a668e3-3078-4f79-bb55-5371336c559d)

You don't have the rights to create a dataset under this namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/app/env/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/datasets/asherisaac/autotrain-data-xonj-hbfr-uuz9

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/env/lib/python3.9/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/app/env/lib/python3.9/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/app/env/lib/python3.9/site-packages/gradio/blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/app/env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/app/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/env/lib/python3.9/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/app/src/autotrain/apps/llm.py", line 40, in start_training
    dset.prepare()
  File "/app/src/autotrain/dataset.py", line 295, in prepare
    preprocessor.prepare()
  File "/app/src/autotrain/preprocessor/text.py", line 219, in prepare
    train_df.push_to_hub(
  File "/app/env/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 5422, in push_to_hub
    repo_id, split, uploaded_size, dataset_nbytes, repo_files, deleted_size = self._push_parquet_shards_to_hub(
  File "/app/env/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 5240, in _push_parquet_shards_to_hub
    api.create_repo(
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 2316, in create_repo
    self.repo_info(repo_id=repo_id, repo_type=repo_type, token=token)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1868, in repo_info
    return method(
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1741, in dataset_info
    hf_raise_for_status(r)
  File "/app/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-650c2a7c-12d6d53e3a4d18c25a3e3a45;f3b71b59-95ca-4a64-9684-10d92113561f)

Repository Not Found for url: https://huggingface.co/api/datasets/asherisaac/autotrain-data-xonj-hbfr-uuz9.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

**Comment by abhishekkrthakur** [comment]
It seems like you used a read-only token for your account when you created this space. you can either create a new autotrain space with a write token or change the token in this existing space by navigating to settings > secrets and then doing a factory reboot. lemme know if that worked.

**Comment by asherisaac** [comment]
It worked, thanks a lot!
