### ISSUE TITLE
Error with message WARNING: Clicking Start Training will incur costs!

### ISSUE THREAD

**Issue by sailendukumar** [huggingface/autotrain-advanced#287]
![HF_issue](https://github.com/huggingface/autotrain-advanced/assets/32447348/43b3b572-8198-42dd-b36e-f27b18a931f0)

Following blog https://huggingface.co/blog/Llama2-for-non-engineers to finetune llama2 model. But training is not getting initiated. Getting error without any mention of reason

**Comment by abhishekkrthakur** [comment]
you can click on logs to get more information about the error. my guesses are: no access to llama models, or no valid payment method in account.

**Comment by Baolalala** [comment]
I got same problem like him and I have checked log, the error messages are :
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1433, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1243, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/app/env/lib/python3.10/site-packages/gradio/components/dataframe.py", line 211, in preprocess
    return pd.DataFrame(x["data"], columns=x.get("headers"))
  File "/app/env/lib/python3.10/site-packages/pandas/core/frame.py", line 806, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "/app/env/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/app/env/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/app/env/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 3 columns passed, passed data had 0 columns

is this means there is something wrong with my data? or other problems?
