### ISSUE TITLE
KeyError: 'text'

### ISSUE THREAD

**Issue by Sequential-circuits** [huggingface/autotrain-advanced#291]
I am getting the below error when using the command

autotrain llm --train --project_name medical --model /ai/text-generation-webui/models/tiiuae_falcon-7b/ --data_path /ai/lixo/ --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 35 --num_train_epochs 3 --trainer sft --model_max_length 1024

]> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/autotrain/trainers/clm/__main__.py", line 300, in train
    trainer.train()
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1870, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/data_loader.py", line 560, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/data_loader.py", line 523, in _fetch_batches
    batches.append(next(iterator))
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/root/anaconda3/lib/python3.9/site-packages/trl/trainer/utils.py", line 482, in __iter__
    buffer.append(self.formatting_func(next(iterator)))
  File "/root/anaconda3/lib/python3.9/site-packages/trl/trainer/utils.py", line 458, in <lambda>
    self.formatting_func = lambda x: x[dataset_text_field]
KeyError: 'text'

I believe this to be because a field in the dataset is corrupted or empty. If yes, there must be a way to just ignore those records?

**Comment by Shantan243** [comment]
@Sequential-circuits: Could you able to fix this issue? if yes, could you please share how did you managed to do the same

**Comment by abhishekkrthakur** [comment]
It means you are not specifying the correct test column. Either specify the text column or make sure there is a column called text in your dataset

**Comment by michaelgruner** [comment]
This is a data formatting problem with your dataset. Are you able to share the first few samples?
