### ISSUE TITLE
Unable to finetune the model ->llama-2-7bn-hf with the dataset of format (prompt,instruction,input, response)

### ISSUE THREAD

**Issue by Shantan243** [huggingface/autotrain-advanced#293]
Following error keeps popping up.. Please help immediately..

......

> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/autotrain/trainers/clm/__main__.py", line 304, in train
    trainer.train()
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1870, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/opt/conda/lib/python3.8/site-packages/accelerate/data_loader.py", line 560, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/data_loader.py", line 523, in _fetch_batches
    batches.append(next(iterator))
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/opt/conda/lib/python3.8/site-packages/trl/trainer/utils.py", line 482, in __iter__
    buffer.append(self.formatting_func(next(iterator)))
  File "/opt/conda/lib/python3.8/site-packages/trl/trainer/utils.py", line 458, in <lambda>
    self.formatting_func = lambda x: x[dataset_text_field]
KeyError: 'text'

.....

**Comment by KabaTubare** [comment]
It needs to be in the alpaca format to work (if you're training llama2)

**Comment by Shantan243** [comment]
Yes, the data is format into alpaca format and feeded to model for finetuning.. I see the same key error raised by other as well, in the issues repo.

Please help..

**Comment by profesanti** [comment]
does the data format change for others models, e.g. Mistral?

**Comment by KabaTubare** [comment]
You have to go to HuggingFace and check out the Mistral model page and then check out the Dataset it was trained on. Once there you will see where you can check the format of the dataset itself. Then you can format your dataset just like it. Also, autotrain is not that great imo. I have not gotten it to work properly on Colab and the cost to do it on the platform can get quite costly. But that's just my opinion

**Comment by ErikBjare** [comment]
@KabaTubare What's better in your opinion?

**Comment by abhishekkrthakur** [comment]
here is a sample dataset: https://huggingface.co/datasets/timdettmers/openassistant-guanaco. the problem is probably you didnt specify `--text-column` manually and it fell back to `text` as default column. Having the dataset in the format specified above wont cause any issues.
