### ISSUE TITLE
torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

### ISSUE THREAD

**Issue by jsr-09** [huggingface/autotrain-advanced#300]
Getting this error since yesterdays update. Tried running on kaggle, colab, saturncloud.every where same error
(T4-XLarge - 4 cores - 16 GB RAM - 1 GPU - 40Gi Disk) aslo tried on kaggles p100 gpu.
Working fine 3-4 days ago

> INFO    Namespace(version=False, model='stabilityai/stable-diffusion-xl-base-1.0', revision=None, tokenizer=None, image_path='/home/jovyan/workspace/images/imgs/', class_image_path=None, prompt='hallow33n ', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, project_name='halloweenn', seed=42, resolution=1024, center_crop=None, train_text_encoder=True, batch_size=1, sample_batch_size=4, epochs=1, num_steps=1500, checkpointing_steps=100000, resume_from_checkpoint=None, gradient_accumulation=4, gradient_checkpointing=True, lr=0.0001, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=True, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=True, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, token='***********************', repo_id='****/*****', push_to_hub=True, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, username=None, func=<ffunc=<function run_dreambooth_command_factory at 0x7f522182b280>)
> INFO    Enabling xformers
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/autotrain/trainers/dreambooth/__main__.py", line 110, in train
    utils.enable_xformers(unet, config)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/autotrain/trainers/dreambooth/utils.py", line 315, in enable_xformers
    unet.enable_xformers_memory_efficient_attention()
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 287, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 203, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

**Comment by abhishekkrthakur** [comment]
did you run autotrain setup command?

**Comment by jsr-09** [comment]
A quick edit the code works on colab but fails on both kaggle and saturn cloud.Can you please provide the fix.
Thankyou

**Comment by abhishekkrthakur** [comment]
then from the error it looks like the gpu is not available. you may try updating pytorch.

**Comment by jsr-09** [comment]
https://www.kaggle.com/code/jsram09/autotrain  this is the code i am running. Also update pytorch. still getting the same error.
