### ISSUE TITLE
torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

### ISSUE THREAD

**Issue by jsr-09** [huggingface/autotrain-advanced#304]
https://www.kaggle.com/code/jsram09/autotrain This is the code I am running. Also updated pytorch to latest version. still getting the same error. please can you tell the mistake in the code

INFO Namespace(version=False, model='stabilityai/stable-diffusion-xl-base-1.0', revision=None, tokenizer=None, image_path='/home/jovyan/workspace/images/imgs/', class_image_path=None, prompt='hallow33n ', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, project_name='halloweenn', seed=42, resolution=1024, center_crop=None, train_text_encoder=True, batch_size=1, sample_batch_size=4, epochs=1, num_steps=1500, checkpointing_steps=100000, resume_from_checkpoint=None, gradient_accumulation=4, gradient_checkpointing=True, lr=0.0001, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=True, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=True, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, token='******************', repo_id='****/', push_to_hub=True, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, username=None, func=<ffunc=<function run_dreambooth_command_factory at 0x7f522182b280>)
INFO Enabling xformers
ERROR train has failed due to an exception:
ERROR Traceback (most recent call last):
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/autotrain/utils.py", line 280, in wrapper
return func(*args, **kwargs)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/autotrain/trainers/dreambooth/main.py", line 110, in train
utils.enable_xformers(unet, config)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/autotrain/trainers/dreambooth/utils.py", line 315, in enable_xformers
unet.enable_xformers_memory_efficient_attention()
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 287, in enable_xformers_memory_efficient_attention
self.set_use_memory_efficient_attention_xformers(True, attention_op)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
fn_recursive_set_mem_eff(module)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
fn_recursive_set_mem_eff(child)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
fn_recursive_set_mem_eff(child)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
fn_recursive_set_mem_eff(child)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 244, in fn_recursive_set_mem_eff
module.set_use_memory_efficient_attention_xformers(valid, attention_op)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
fn_recursive_set_mem_eff(module)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
fn_recursive_set_mem_eff(child)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
fn_recursive_set_mem_eff(child)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 244, in fn_recursive_set_mem_eff
module.set_use_memory_efficient_attention_xformers(valid, attention_op)
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 203, in set_use_memory_efficient_attention_xformers
raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

**Comment by jvachez** [comment]
I think autotrain advanced is now incompatible with latest version of some dependencies.

**Comment by abhishekkrthakur** [comment]
> I think autotrain advanced is now incompatible with latest version of some dependencies.

nope

**Comment by jsr-09** [comment]
> > I think autotrain advanced is now incompatible with latest version of some dependencies.
> 
> nope

please provide a code to run autotrain in kaggle.Please

**Comment by jsr-09** [comment]
!pip install -U xformers==0.0.22 
fixes everything for me
Thankyou @abhishekkrthakur

**Comment by jvachez** [comment]
Yes, autotrain advanced is now incompatible with latest version of Xformers.

**Comment by abhishekkrthakur** [comment]
Latest version of xformers is only incompatible with colab and autotrain. This has already been addressed in latest autotrain release and setup command now has a --colab argument.
