### ISSUE TITLE
CUDA Setup failed despite GPU being available

### ISSUE THREAD

**Issue by LucianoSP** [huggingface/autotrain-advanced#311]
Im trying to run autotrain on my  Win11 with RTX 4090 and having issues. 

I have created a new python 3.11.5 conda env, installed autotrain-advanced, run autotrain setup --update-torch and installed perfectly. 

When I try to run the command:
autotrain llm --train --project_name "zephyr_cb_test1" --model HuggingFaceH4/zephyr-7b-alpha --data_path timdettmers/openassistant-guanaco --text_column text --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 4 --num_train_epochs 3 --trainer sft --model_max_length 2048 --block_size 2048 > training.log &

I get this error:

```
================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=122
================================================================================


  warn((f'\n\n{"="*80}\n'
C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: C:\Users\PC\.conda\envs\autotrain did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC\.conda\envs\autotrain\Scripts\autotrain.exe\__main__.py", line 7, in <module>
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\autotrain\cli\autotrain.py", line 48, in main
    command.run()
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\autotrain\cli\run_llm.py", line 452, in run
    from autotrain.trainers.clm.__main__ import train as train_llm
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\autotrain\trainers\clm\__main__.py", line 13, in <module>
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\peft\auto.py", line 31, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\peft\mapping.py", line 23, in <module>
    from .peft_model import (
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\peft\peft_model.py", line 38, in <module>
    from .tuners import (
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\peft\tuners\lora\__init__.py", line 21, in <module>
    from .model import LoraModel
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\peft\tuners\lora\model.py", line 45, in <module>
    import bitsandbytes as bnb
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

Then I execute the command python -m bitsandbytes and get this error:

```
python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('C'), WindowsPath('/Users/PC/.conda/envs/autotrain/lib')}
C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: C:\Users\PC\.conda\envs\autotrain did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda122.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\PC\.conda\envs\autotrain\Lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```
I tried to find the file libcudart.so but didn´t find it. 

I have this version of CUDA installed
```
(autotrain) D:\Código\autotrain>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:09:35_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```

Is this compatible with windows?
How can I fix it? 
Thanks

**Comment by psdwizzard** [comment]
I am having these issues to on windows 10 with a 3060 ti
