### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Fawzan09** [huggingface/autotrain-advanced#318]
ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 273, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 350, in train
    for step, batch in enumerate(self.train_dataloader):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 461, in __iter__
    next_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/datasets.py", line 167, in __getitem__
    instance_image = Image.open(self.instance_images_path[index % self.num_instance_images])
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/content/images/.ipynb_checkpoints'

**Comment by jke94** [comment]
Hi @Fawzan09! You are not alone, I have the save issue with the collab for AutoTrain_Dreambooth. I have created my 'images' folder but I do not understand what is the problem.

**Comment by abhishekkrthakur** [comment]
you really need to see hidden files inside the images folder. if the checkpoints folder has been created by colab there, you need to remove it. its a non issue

**Comment by hammer-mt** [comment]
Colab just adds it back in

**Comment by abhishekkrthakur** [comment]
show hidden files >> right click, remove. simple. its a colab problem. just dont open the folder and you will be fine.

**Comment by hammer-mt** [comment]
For some reason it doesn't allow you to delete. But if you create a new
folder and don't open it, it works.
