### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by Baolalala** [huggingface/autotrain-advanced#319]
Traceback (most recent call last):
  File "/app/env/bin/autotrain", line 33, in <module>
    sys.exit(load_entry_point('autotrain-advanced', 'console_scripts', 'autotrain')())
  File "/app/src/autotrain/cli/autotrain.py", line 48, in main
    command.run()
  File "/app/src/autotrain/cli/run_app.py", line 57, in run
    from ..apps.main import main
  File "/app/src/autotrain/apps/main.py", line 10, in <module>
    llm = llm()
  File "/app/src/autotrain/apps/llm.py", line 52, in main
    user_token, valid_can_pay, who_is_training = common.user_validation()
  File "/app/src/autotrain/apps/common.py", line 22, in user_validation
    raise ValueError("Please login with a write token.")
ValueError: Please login with a write token.
ERROR conda.cli.main_run:execute(49): `conda run /bin/bash -c autotrain setup && autotrain app --port 7860` failed. (See above for error)

**Comment by abhishekkrthakur** [comment]
please supply your write token from huggingface settings as HF_TOKEN in secrets
