### ISSUE TITLE
ERROR   train has failed due to an exception

### ISSUE THREAD

**Issue by norflin321** [huggingface/autotrain-advanced#330]
I get this error when trying to run cells. 2 hours ago it was fine(
```
Steps:   0% 0/500 [00:00<?, ?it/s]> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 311, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 404, in train
    model_pred = self._get_model_pred(batch, channels, noisy_model_input, timesteps, bsz)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 302, in _get_model_pred
    model_pred = self.unet(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 659, in forward
    return model_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 647, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 958, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 1076, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformer_2d.py", line 303, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 251, in checkpoint
    return _checkpoint_without_reentrant(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 432, in _checkpoint_without_reentrant
    output = function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention.py", line 218, in forward
    attn_output = self.attn2(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 417, in forward
    return self.processor(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 952, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 326, in _memory_efficient_attention
    return _fMHA.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 42, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 348, in _memory_efficient_attention_forward_requires_grad
    inp.validate_inputs()
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/common.py", line 112, in validate_inputs
    raise ValueError(
ValueError: Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float32
  key.dtype  : torch.float16
  value.dtype: torch.float16
```

**Comment by abhishekkrthakur** [comment]
did you run `autotrain setup --colab` if you are on colab?

**Comment by abhishekkrthakur** [comment]
also, which model gives this error?

**Comment by papanton** [comment]
having the same issue. I am using dreambooth with sdxl-1.0 colab. V100 and T4 GPUs have the same issue

**Comment by norflin321** [comment]
i do run in colab, first 2 cells give no errors
```
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
> INFO    Installing latest xformers
> INFO    Successfully installed latest xformers
```
i am using `stabilityai/stable-diffusion-xl-base-1.0`

**Comment by papanton** [comment]
I think its the warning. Something off with `torchvision` hence the error?

**Comment by norflin321** [comment]
setting `USE_XFORMERS = False` results in no errors, but I'm worried that this will affect the quality of the result?

**Comment by abhishekkrthakur** [comment]
what if you add pip install -U xformers right before the training cell?

**Comment by norflin321** [comment]
> what if you add pip install -U xformers right before the training cell?

RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA major versions. PyTorch has CUDA Version=12.1 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.

**Comment by norflin321** [comment]
> yeah. its colab stuff. i tried locally with sdxl and sd1.5 and both seem to be working fine. ill take a look. disabling xformers will take more memory and produce same results btw.

Thanks, I'll leave a comment as soon as I find a way to fix it

**Comment by PoCk3T** [comment]
@abhishekkrthakur looks like your commit few hours ago broke AutoTrain for many of us FYI/FYA

**Comment by abhishekkrthakur** [comment]
seems like just xformers isnt working. right?

**Comment by PoCk3T** [comment]
disabling xformers doesn't help for me, mixed feedbacks above

**Comment by abhishekkrthakur** [comment]
ill take a look at colab notebook in that case. the release was only done after the local tests passed. for now, you can also pin autotrain to previous version!

**Comment by PoCk3T** [comment]
Thank you @abhishekkrthakur 
Indeed, sometime I forget the basic, but you were right, changing 
```!pip install -U autotrain-advanced > install_logs.txt```
to
```!pip install -U autotrain-advanced==0.6.42 > install_logs.txt```

**Comment by abhishekkrthakur** [comment]
colab notebook has temporarily been fixed by disabling xformers

**Comment by divyanshusingh5** [comment]
i am facing same issue for data like  i tried 
!pip install -U autotrain-advanced > install_logs.txt
but still having same error 

![image](https://github.com/huggingface/autotrain-advanced/assets/96836586/57838e00-2ac7-41aa-94c0-0a245a78ccb6)
its showing 
ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 56, in train
    train_data = load_dataset(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1815, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1512, in dataset_module_factory
    raise e1 from None
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1479, in dataset_module_factory
    raise e
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1453, in dataset_module_factory
    dataset_info = hf_api.dataset_info(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'data/'.

[23]
0s

**Comment by frameartist** [comment]
> Actually i wanted to use lama for summarizing medical dialogue i tried this and i am facing same issue for data like i tried !pip install -U autotrain-advanced > install_logs.txt but still having same error ..
> 
> ![image](https://private-user-images.githubusercontent.com/96836586/281299022-57838e00-2ac7-41aa-94c0-0a245a78ccb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTU4MjIsIm5iZiI6MTczMTM5NTUyMiwicGF0aCI6Ii85NjgzNjU4Ni8yODEyOTkwMjItNTc4MzhlMDAtMmFjNy00MWFhLTk0YzAtMGEyNDVhNzhjY2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA3MTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZGQ5YjhmZTUxOWRhZGU0YTg2NTJjOGRkOGEyZjE0MDIwZWVlOTBlOWE1NGE4MWJjYTM5OWFmM2VkMTQzMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NTNVeMLxJ1iYYGk7SlBq1aFYSrTO8q5TGaJdqjRhUGs) its showing ERROR train has failed due to an exception:
> 
> > ERROR   Traceback (most recent call last):
> > File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
> > return func(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/**main**.py", line 56, in train
> > train_data = load_dataset(
> > File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 2129, in load_dataset
> > builder_instance = load_dataset_builder(
> > File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1815, in load_dataset_builder
> > dataset_module = dataset_module_factory(
> > File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1512, in dataset_module_factory
> > raise e1 from None
> > File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1479, in dataset_module_factory
> > raise e
> > File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1453, in dataset_module_factory
> > dataset_info = hf_api.dataset_info(
> > File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
> > validate_repo_id(arg_value)
> > File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 164, in validate_repo_id
> > raise HFValidationError(
> > huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'data/'.
> 
> [23] 0s

I'm a bit late here but for those struggling with colab and AutoTrain_LLM.ipynb, colab is using `content` for the path of the uploaded files. you might want to look at the generated conf.yaml and change `path: data/` to `path: /content/` or `path: /content` (both options sometimes don't work, don't know why, so better test both).
