### ISSUE TITLE
Training failed

### ISSUE THREAD

**Issue by electron271** [huggingface/autotrain-advanced#351]
```
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/app/src/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/app/src/autotrain/trainers/clm/__main__.py", line 161, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/app/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/app/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2714, in from_pretrained
    raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
```

Happens when using the docker image on huggingface, free cpu tier

**Comment by eviIgenius** [comment]
I think required libraries aren't install such as accelerate & bitsandbytes

Try:
`pip install accelerate`
`pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes`

Otherwise try:

```
!pip install git+https://github.com/huggingface/transformers
!pip install -q peft  accelerate bitsandbytes safetensors
!pip install huggingface_hub
```

Also, there maybe a possible that if you are running code on google colab , you may have to restart runtime if you have updated some library.

**Comment by abhishekkrthakur** [comment]
you cannot train llms on free cpu tear

**Comment by electron271** [comment]
oh ok
