### ISSUE TITLE
Out of memory Error MultiGPU

### ISSUE THREAD

**Issue by luisgg98** [huggingface/autotrain-advanced#352]
Good afternoon I am facing the issue of CUDA out of memory when I am try to finetune the model "mistralai/Mistral-7B-v0.1". 
Before running the command I set the visible cuda devices for the command.
```shell
export CUDA_VISIBLE_DEVICES=0,1
``` 
I have 2 GPUs available although when I run the command autotrain I get this error.  

```shell
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:17:00.0 Off |                    0 |
| N/A   50C    P0              87W / 300W |    901MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          Off | 00000000:65:00.0 Off |                    0 |
| N/A   38C    P0              54W / 300W |      7MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

```
After running accelerate env:
```shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.24.0
- Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- Numpy version: 1.26.1
- PyTorch version (GPU?): 2.1.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 503.32 GB
- GPU type: NVIDIA A100 80GB PCIe
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: True
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 0,1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```
My Autrotrain version:  
Autotrain version: 0.6.44

```shell
[2023-11-16 14:36:44,095] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> INFO    Running LLM
> INFO    Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='data/', train_split='train', valid_split=None, text_column='text', rejected_text_column='rejected', prompt_text_column='prompt', model='mistralai/Mistral-7B-v0.1', model_ref=None, learning_rate=0.0002, num_train_epochs=1, train_batch_size=1, warmup_ratio=0.1, gradient_accumulation_steps=4, optimizer='adamw_torch', scheduler='linear', weight_decay=0.01, max_grad_norm=1.0, seed=42, add_eos_token=False, block_size=1024, use_peft=False, lora_r=16, lora_alpha=32, lora_dropout=0.05, logging_steps=-1, project_name='my_autotrain_mistral_7b_modelllm', evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, fp16=False, push_to_hub=False, use_int8=False, model_max_length=1024, repo_id=None, use_int4=False, trainer='default', target_modules=None, merge_adapter=False, token=None, backend='default', username=None, use_flash_attention_2=False, log='none', disable_gradient_checkpointing=False, dpo_beta=0.1, func=<function run_llm_command_factory at 0x7f2d2f43d6c0>)
[2023-11-16 14:36:49,864] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 14:36:49,864] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> INFO    loading dataset from csv
> INFO    loading dataset from csv
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.96s/it]
> INFO    Using block size 1024
Running tokenizer on train dataset: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 117/117 [00:00<00:00, 5667.98 examples/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.96s/it]
> INFO    Using block size 1024
Running tokenizer on train dataset: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 117/117 [00:00<00:00, 5534.63 examples/s]
Grouping texts in chunks of 1024 (num_proc=4): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 117/117 [00:00<00:00, 221.93 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):   0%|                                                                                                                           | 0/117 [00:00<?, ? examples/s]/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/datasets/table.py:1395: FutureWarning: promote has been superseded by mode='default'.
  block_group = [InMemoryTable(cls._concat_blocks(list(block_group), axis=axis))]
/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)
> INFO    creating trainer
Grouping texts in chunks of 1024 (num_proc=4): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 117/117 [00:00<00:00, 218.13 examples/s]
/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/datasets/table.py:1395: FutureWarning: promote has been superseded by mode='default'.
  block_group = [InMemoryTable(cls._concat_blocks(list(block_group), axis=axis))]
/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)
> INFO    creating trainer
  0%|                                                                                                                                                                                   | 0/1 [00:00<?, ?it/s]/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/autotrain/trainers/clm/__main__.py", line 440, in train
    trainer.train()
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/transformers/trainer.py", line 2787, in training_step
    self.accelerator.backward(loss)
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/accelerate/accelerator.py", line 1989, in backward
    loss.backward(**kwargs)
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 288, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/my_user/.conda/envs/env-llm-test/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacty of 79.15 GiB of which 73.75 MiB is free. Process 297070 has 888.00 MiB memory in use. Including non-PyTorch memory, this process has 78.19 GiB memory in use. Of the allocated memory 77.00 GiB is allocated by PyTorch, and 84.87 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

  0%|                                                                                                                                                                                   | 0/1 [00:03<?, ?it/s]
```

Autotrain command I am running:
```bash
# Project Config
project_name='my_autotrain_mistral_7b_modelllm'
model_name='mistralai/Mistral-7B-v0.1'
# Data for Training
data_path="data/"
text_column="text"

# Push to Hub
push_to_hub=false
hf_token="hf_XXXXX"

# Hyperparameters
learning_rate=2e-4
num_epochs=1
batch_size=1
block_size=1024
trainer="sft"
warmup_ratio=0.1
weight_decay=0.01
gradient_accumulation=4
use_fp16=false
use_peft=false
use_int4=false
lora_r=16
lora_alpha=32
lora_dropout=0.05

# Set environment variables
export PROJECT_NAME="$project_name"
export MODEL_NAME="$model_name"
export HF_TOKEN="$hf_token"
export LEARNING_RATE="$learning_rate"
export NUM_EPOCHS="$num_epochs"
export BATCH_SIZE="$batch_size"
export BLOCK_SIZE="$block_size"
export WARMUP_RATIO="$warmup_ratio"
export WEIGHT_DECAY="$weight_decay"
export GRADIENT_ACCUMULATION="$gradient_accumulation"
export USE_FP16="$use_fp16"
export USE_PEFT="$use_peft"
export USE_INT4="$use_int4"
export LORA_R="$lora_r"
export LORA_ALPHA="$lora_alpha"
export LORA_DROPOUT="$lora_dropout"

autotrain llm \
--train \
--model ${MODEL_NAME} \
--project-name ${PROJECT_NAME} \
--data-path ${data_path} \
--text-column ${text_column} \
--lr ${LEARNING_RATE} \
--batch-size ${BATCH_SIZE} \
--epochs ${NUM_EPOCHS} \
--block-size ${BLOCK_SIZE} \
--warmup-ratio ${WARMUP_RATIO} \
--lora-r ${LORA_R} \
--lora-alpha ${LORA_ALPHA} \
--lora-dropout ${LORA_DROPOUT} \
--weight-decay ${WEIGHT_DECAY} \
--gradient-accumulation ${GRADIENT_ACCUMULATION} \
$( [[ "$USE_FP16" == "True" ]] && echo "--fp16" ) \
$( [[ "$USE_PEFT" == "True" ]] && echo "--use-peft" ) \
$( [[ "$USE_INT4" == "True" ]] && echo "--use-int4" ) \
```
Sorry but, any ideas of why is this happenning?
Thank you very much!

**Comment by xihajun** [comment]
maybe you can set `use_fp16=true`

**Comment by luisgg98** [comment]
> maybe you can set `use_fp16=true`

Hi! I tried to add that flag but despite adding it is not working sorry 😢

**Comment by xihajun** [comment]
Maybe try to enable this as well?
```
use_int4=true
```
and also try `--use_flash_attention_2` if you have the package installed

**Comment by abhishekkrthakur** [comment]
7B should work perfectly fine on your setup. Maybe try:
--use-peft
--use-int4
--fp16
