### ISSUE TITLE
Auto Train | Sequence to Sequence

### ISSUE THREAD

**Issue by chintanckg** [huggingface/autotrain-advanced#363]
Task Sequence to Sequence

Dataset format: CSV format and it has two columns: 'text' and 'target'.

Hardware - A100

Current Result: 500 Error

Logs from the container: 

```
INFO:     10.16.34.18:1657 - "POST /create_project HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/app/env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/src/autotrain/app.py", line 252, in handle_form
    dset.prepare()
  File "/app/src/autotrain/dataset.py", line 296, in prepare
    preprocessor.prepare()
  File "/app/src/autotrain/preprocessor/text.py", line 282, in prepare
    train_df, valid_df = self.split()
  File "/app/src/autotrain/preprocessor/text.py", line 260, in split
    train_df, valid_df = train_test_split(
  File "/app/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/app/env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2638, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
  File "/app/env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 1726, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/app/env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2115, in _iter_indices
    raise ValueError(
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
> INFO    Dataset: quote_intake (seq2seq)
Train data: [<tempfile.SpooledTemporaryFile object at 0x7faa6f13b970>]
Valid data: []
Column mapping: {'text': 'text', 'label': 'target'}

INFO:     10.16.34.18:14877 - "POST /create_project HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/app/env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/src/autotrain/app.py", line 252, in handle_form
    dset.prepare()
  File "/app/src/autotrain/dataset.py", line 296, in prepare
    preprocessor.prepare()
  File "/app/src/autotrain/preprocessor/text.py", line 282, in prepare
    train_df, valid_df = self.split()
  File "/app/src/autotrain/preprocessor/text.py", line 260, in split
    train_df, valid_df = train_test_split(
  File "/app/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/app/env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2638, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
  File "/app/env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 1726, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/app/env/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2115, in _iter_indices
    raise ValueError(
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
```

**Comment by chintanckg** [comment]
Okay

**Comment by chintanckg** [comment]
Now getting authentication error:

```
Repository Not Found for url: https://huggingface.co/api/datasets/gaussfer/some-repo-name
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
```

I have added a token in the autotrain config, please help.

**Comment by abhishekkrthakur** [comment]
you dont need to add token there. you need to use your write token when creating the template see hf.co/docs/autotrain getting started.

**Comment by chintanckg** [comment]
Thanks @abhishekkrthakur , that helped.

Now, getting this new error:

```> INFO    [{"seed":42,"lr":0.00005,"epochs":3,"max_seq_length":128,"max_target_length":128,"batch_size":8,"warmup_ratio":0.1,"gradient_accumulation":1,"optimizer":"adamw_torch","scheduler":"linear","weight_decay":0,"max_grad_norm":1,"logging_steps":-1,"evaluation_strategy":"epoch","auto_find_batch_size":false,"fp16":false,"save_total_limit":1,"save_strategy":"epoch","use_peft":false,"use_int8":false,"lora_r":16,"lora_alpha":32,"lora_dropout":0.05,"target_modules":[],"model_choice":"google\/flan-ul2","param_choice":"manual","backend":"A100 Large"}]
INFO:     10.16.34.18:25594 - "POST /create_project HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/app/env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/src/autotrain/app.py", line 301, in handle_form
    ids = project.create()
  File "/app/src/autotrain/project.py", line 179, in create
    return self.create_spaces()
  File "/app/src/autotrain/project.py", line 164, in create_spaces
    raise NotImplementedError
NotImplementedError```

**Comment by abhishekkrthakur** [comment]
this shouldnt happen. will be fixed in a few hours. thanks for pointing this out and apologies for the inconvenience.

**Comment by chintanckg** [comment]
Thanks, @abhishekkrthakur, one humble request to do one round of end-to-end sanity testing for private hf space with autotrain for seq2seq, we have subscribed for large A100s, every attempt we make it's heavily billed per hour irrespective of errors.

**Comment by abhishekkrthakur** [comment]
fixed, tested and deployed.

**Comment by chintanckg** [comment]
I factory rebuilt the space, also created a new one, it goes in "Building" state indefinetely

**Comment by abhishekkrthakur** [comment]
ill let the hub team know.

**Comment by abhishekkrthakur** [comment]
sometimes when theres a big queue, building takes time.

**Comment by chintanckg** [comment]
It's still in the queue I guess, have restarted the space, will wait for sometime, will keep posted anyways.

**Comment by abhishekkrthakur** [comment]
weird, can you do factory reboot instead of normal restart ?

**Comment by chintanckg** [comment]
Worked.. However, it says no enough hardware capacity. Will share updates once the hardware pool lightens up!

**Comment by chintanckg** [comment]
Tried once again, hardware error gone, once again stuck in building state

**Comment by chintanckg** [comment]
https://www.loom.com/share/524218e75dbd4f8c9d5307f7cb582851?sid=c658c594-e6b6-4934-957e-e05ca1ba4e73

**Comment by abhishekkrthakur** [comment]
could you please share it with website@hf.co ?

**Comment by chintanckg** [comment]
Okay

**Comment by chintanckg** [comment]
resolved.

**Comment by chintanckg** [comment]
@abhishekkrthakur , turns out that we need atleast 4xA100s, however there is option to get more than 1xA100. Please advise on a plan, thanks.

**Comment by chintanckg** [comment]
Their opinion is that multiple A100s are for inference endpoints only, for auto train generally 1xA100 is allowed (this is slightly not the way I understand), they asked to justify why we need more compute, I have share proper details yesterday morning, yet to hear back.
