### ISSUE TITLE
Cannot access gated repo Llama-2-7b-hf

### ISSUE THREAD

**Issue by MatteoWood** [huggingface/autotrain-advanced#365]
I'm trying to train a binary text classificator but as soon as I start the training with meta-llama/Llama-2-7b-hf model, the space pauses with the following error.
I have been granted the access to every Llama model (- Gated model You have been granted access to this model -). With Bert I had no problems.

> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/app/env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/meta-llama/Llama-2-7b-hf/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 430, in cached_file
    resolved_file = hf_hub_download(
  File "/app/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1346, in hf_hub_download
    raise head_call_error
  File "/app/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/app/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/app/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1608, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/app/env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 277, in hf_raise_for_status
    raise GatedRepoError(message, response) from e
huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-65679e59-1b9ceafa62ea575641e21697;cf8ac436-b333-4f2c-a704-8b64d5d103b9)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-2-7b-hf/resolve/main/config.json.
Repo model meta-llama/Llama-2-7b-hf is gated. You must be authenticated to access it.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/src/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/app/src/autotrain/trainers/text_classification/__main__.py", line 87, in train
    model_config = AutoConfig.from_pretrained(config.model, num_labels=num_classes)
  File "/app/env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1048, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/app/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 622, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/app/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 677, in _get_config_dict
    resolved_config_file = cached_file(
  File "/app/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 445, in cached_file
    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to request access at https://huggingface.co/meta-llama/Llama-2-7b-hf and pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`.

> INFO    Pausing space...

**Comment by tamastarjanyi** [comment]
Did you try to use --token parameter?
`autotrain .... --token your_hf_token`

**Comment by MatteoWood** [comment]
I'm trying to train the model on a HF autotrain space, not locally.

**Comment by abhishekkrthakur** [comment]
are you still facing this issue? ive trained llama several times in the last week but didnt get any issue.

**Comment by MatteoWood** [comment]
I tried again now, after finishing downloading the shards the traceback is the following:

INFO:     10.16.18.44:10615 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJyZWFkIjp0cnVlLCJvbkJlaGFsZk9mIjp7Il9pZCI6IjY1NjY3MGNmNGY2ZWM3MjAxNzRkYzg5ZSIsInVzZXIiOiJNYXR0ZW9Xb29kIn0sImlhdCI6MTcwMjk3ODI3MSwic3ViIjoiL3NwYWNlcy9NYXR0ZW9Xb29kL2F1dG90cmFpbi1sbGFtYS1zZXhpc20tdGVzdC0wIiwiZXhwIjoxNzAzMDY0NjcxLCJpc3MiOiJodHRwczovL2h1Z2dpbmdmYWNlLmNvIn0.MpzFHzR3HF4IG1iMQKQCX7c59B88HZSWZKRWGfMVveOhu8pQbETNL0vkVZDVf0NLbBPmDygF7c1TCIRSZmvTBw HTTP/1.1" 200 OK
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/app/env/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/app/env/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/app/env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/app/env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/app/env/bin/python', '-m', 'autotrain.trainers.text_classification', '--training_config', '/tmp/model/training_params.json']' died with <Signals.SIGKILL: 9>.
> INFO    Process 53 is already completed. Skipping...
> INFO    No running jobs found. Shutting down the server.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [35]

But the space keeps the running status and it does not pause.

**Comment by MatteoWood** [comment]
I used the autotrain space on hf. Here the training params:

Training config: {'data_path': 'MatteoWood/autotrain-data-llama-sexism-test', 'model': 'meta-llama/Llama-2-7b-hf', 'lr': 5e-05, 'epochs': 5, 'max_seq_length': 128, 'batch_size': 8, 'warmup_ratio': 0.1, 'gradient_accumulation': 1, 'optimizer': 'adamw_torch', 'scheduler': 'linear', 'weight_decay': 0.0, 'max_grad_norm': 1.0, 'seed': 42, 'train_split': 'train', 'valid_split': 'validation', 'text_column': 'autotrain_text', 'target_column': 'autotrain_label', 'logging_steps': -1, 'project_name': '/tmp/model', 'auto_find_batch_size': False, 'mixed_precision': None, 'save_total_limit': 1, 'save_strategy': 'epoch', 'token': '*****', 'push_to_hub': True, 'repo_id': 'MatteoWood/llama-sexism-test-0', 'evaluation_strategy': 'epoch', 'username': 'MatteoWood', 'log': 'none'}

**Comment by abhishekkrthakur** [comment]
okay. it seems like your original issue is resolved. 
regarding the error after/while loading checkpoint shards, it seems like the process went out of memory and got killed. i'll fix the space to pause in this scenario but thats a different issue.
Also, i was not able to find parameters like quantization & peft in the dict you shared. are you running an older version? you can update the base space by doing a factory rebuild.

with your parameters and with quantization: int4, peft: true, i was able to train a llama2-7b on A10g

**Comment by MatteoWood** [comment]
I updated the autotrain space but now I cannot insert manually the model anymore. I can only pick one in the list and llama is not present for text classification tasks... probably that was the problem. May I know why I cannot train llama for text classification?

**Comment by abhishekkrthakur** [comment]
text classification tasks can only use models that support text classification. why would you want to use llama for text classification and not a model like deberta? anyways, if supporting custom/extra models is your issue, please create a new feature request issue and we can add that feature.
