### ISSUE TITLE
[bug] Finetuning on a Trained model

### ISSUE THREAD

**Issue by xihajun** [huggingface/autotrain-advanced#366]
I have a trained `model A` based on mistral7b, and I finetune it on the trained `model A` and got `model B`. Then if I tried to based on `model B` to finetune a `model C`, I got the error below.

```
     +-------------------------+
     |                         |
     |    Mistral7B            |
     |   Pretrained Model      |
     |         |               |
     |         v               |
     |     +--------+          |
     |     | Model A|          |
     |     +--------+          |
     |         |               |
     |         v               |
     |     +--------+          |
     |     | Model B|          |
     |     +--------+          |
     |         |               |
     |         v               |
     |         ERROR           |
     |                         |
     +-------------------------+
```

I think it might be related the adapter loading process?

```
> INFO    creating trainer
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autotrain/trainers/clm/__main__.py", line 440, in train
    trainer.train()
  File "/usr/local/lib/python3.11/dist-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/trainer.py", line 1726, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py", line 1288, in prepare
    result = tuple(
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py", line 1289, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py", line 1094, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py", line 1433, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/distributed.py", line 697, in __init__
    self._log_and_throw(
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/distributed.py", line 1037, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel's input module must be on the same type of devices, but input module parameters locate in {'cuda', 'cpu'}.
```

**Comment by abhishekkrthakur** [comment]
It seems like you have entered _Inception_ :P 

Is model B public so i can give it a try?

**Comment by xihajun** [comment]
> It seems like you have entered Inception :P

Try this one: `xihajun/autotrain_trained1`?

I think maybe the problem is I manually copy the `config.json` from the original base model `mistralai/Mistral-7B-v0.1`, instead of using the `--merge-adapter`. If the adapter is being merged to the base model, then it should work fine.

**Comment by abhishekkrthakur** [comment]
ohh just copying config.json isnt going to work. you need to use merge adapter argument or merge manually at the end of training. see this to merge after training: https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter

**Comment by xihajun** [comment]
> ohh just copying config.json isnt going to work. you need to use merge adapter argument or merge manually at the end of training. see this to merge after training: [huggingface.co/spaces/autotrain-projects/llm-merge-adapter](https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter)

Thanks a lot @abhishekkrthakur 

I will close this issue now
