### ISSUE TITLE
'DreamBoothTrainingParams' object has no attribute 'model_fields'

### ISSUE THREAD

**Issue by deshpandehn** [huggingface/autotrain-advanced#374]
Hello,

I get the following error while trying the python notebook AutoTrain_Dreambooth on google collab. I would highly appreciate your help.

Thanks and regards,
Hrishikesh

Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 48, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_dreambooth.py", line 473, in run
    params = DreamBoothTrainingParams(**vars(self.args))
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 44, in __init__
    defaults = set(self.model_fields.keys())
AttributeError: 'DreamBoothTrainingParams' object has no attribute 'model_fields'

**Comment by abhishekkrthakur** [comment]
what's the version of autotrain-advanced that you are using? 
`autotrain --version`

**Comment by abhishekkrthakur** [comment]
fixed in version 0.6.49+
