### ISSUE TITLE
No GPU/MPS device found. LLM training requires an accelerator

### ISSUE THREAD

**Issue by s0569591** [huggingface/autotrain-advanced#382]
Hello, I am using a Windows 11 with NVIDIA GeForce RTX 3080 Laptop GPU, but still, no GPU can be found. 
I receive this error message when running autotrain llm:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HTW\anaconda3\Scripts\autotrain.exe\__main__.py", line 7, in <module>
  File "C:\Users\HTW\anaconda3\Lib\site-packages\autotrain\cli\autotrain.py", line 47, in main
    command = args.func(args)
              ^^^^^^^^^^^^^^^
  File "C:\Users\HTW\anaconda3\Lib\site-packages\autotrain\cli\run_llm.py", line 14, in run_llm_command_factory
    return RunAutoTrainLLMCommand(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HTW\anaconda3\Lib\site-packages\autotrain\cli\run_llm.py", line 473, in __init__
    raise ValueError("No GPU/MPS device found. LLM training requires an accelerator")
ValueError: No GPU/MPS device found. LLM training requires an accelerator

How can i fix this problem?

Thanks

**Comment by abhishekkrthakur** [comment]
The error is straightforward. You need a GPU or MPS device to train LLM models.

**Comment by s0569591** [comment]
Thank you for your answer, but I do have a GPU: NVIDIA GeForce RTX 3080 Laptop GPU. 
Does the fine-tuning with autotrain not work with my GPU?

**Comment by nsoticek** [comment]
same
`raise ValueError("No GPU/MPS device found. LLM training requires an accelerator")
ValueError: No GPU/MPS device found. LLM training requires an accelerator`

![image](https://github.com/huggingface/autotrain-advanced/assets/60920484/ef0f3166-151e-4503-a2bf-d135899c585b)

**Comment by abhishekkrthakur** [comment]
should be fixed now
