### ISSUE TITLE
Train error when trying to fine tune Meditron-7B

### ISSUE THREAD

**Issue by Duathphoenix98** [huggingface/autotrain-advanced#386]
Hello,

I'm getting the following error when trying to finetune Meditron-7b model:

> INFO    Running LLM
> INFO    Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='data/', train_split='train', valid_split=None, text_column='text', rejected_text_column='rejected', prompt_text_column='prompt', model='TheBloke/meditron-7B-GGUF/meditron-7b.Q5_K_M.gguf', model_ref=None, learning_rate=0.0002, num_train_epochs=1, train_batch_size=1, warmup_ratio=0.1, gradient_accumulation_steps=4, optimizer='adamw_torch', scheduler='linear', weight_decay=0.01, max_grad_norm=1.0, seed=42, add_eos_token=False, block_size=1024, use_peft=True, lora_r=16, lora_alpha=32, lora_dropout=0.05, logging_steps=-1, project_name='meditron_finetune', evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, fp16=True, push_to_hub=False, use_int8=False, model_max_length=1024, repo_id=None, use_int4=True, trainer='default', target_modules=None, merge_adapter=False, token=None, backend='default', username=None, use_flash_attention_2=False, log='none', disable_gradient_checkpointing=False, dpo_beta=0.1, func=<function run_llm_command_factory at 0x78a92b24e9e0>)
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 62, in train
    train_data = load_dataset(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1815, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1512, in dataset_module_factory
    raise e1 from None
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1479, in dataset_module_factory
    raise e
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1453, in dataset_module_factory
    dataset_info = hf_api.dataset_info(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'data/'.

Any help is appreciated, Thanks.

**Comment by abhishekkrthakur** [comment]
gguf is not supported.
