### ISSUE TITLE
AutoTrain Problems with autotrain-advanced

### ISSUE THREAD

**Issue by vishalmysore** [huggingface/autotrain-advanced#392]
I am trying to execute the example from as mentioned in this link https://colab.research.google.com/github/huggingface/autotrain-advanced/blob/main/colabs/AutoTrain_LLM.ipynb

INFO    Using block size 1024
Running tokenizer on train dataset: 100% 7/7 [00:00<00:00, 91.19 examples/s]
Grouping texts in chunks of 1024 (num_proc=4): 100% 7/7 [00:00<00:00, 22.64 examples/s]
INFO    creating trainer
ERROR   train has failed due to an exception:
ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/main.py", line 440, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1605, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 848, in get_train_dataloader
    dataloader_params["sampler"] = self._get_train_sampler()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 819, in _get_train_sampler
    return RandomSampler(self.train_dataset)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 107, in init
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by abhishekkrthakur** [comment]
you need more data. see previous issues.

**Comment by vishalmysore** [comment]
I have around 50 rows of data , will add more and try
