### ISSUE TITLE
Tabular Classification: TypeError: __init__() got an unexpected keyword argument 'local'

### ISSUE THREAD

**Issue by mikeagz** [huggingface/autotrain-advanced#403]
I have installed autotrain as:

```
conda env create -n autotrain_env python==3.9
conda activate autotrain_env
$env:HF_TOKEN='XX...X'
$env:AUTOTRAIN_LOCAL=1
```

Then run the command:

`autotrain app`

There is a sample of my csv data:

```
id,EDAD,INGRE,GENERO,ECIVIL,HIJOS,NUMTDC,FPAGO,HIPOTECA,TIPCRED,CREDITOS,target
0,44.0,59944.0,m,Casado,1,2,Mensual,s,1,0,2
```

![image](https://github.com/huggingface/autotrain-advanced/assets/150627929/8dd52add-d1fd-48f3-b370-6372b7ad59c0)

When I "Start training" the error is launched:

```
> (autotrain_env)  migue@DESKTOP-KACT01N   ~    autotrain app
> ⚠️ WARNING | 2023-12-18 15:13:18 | autotrain.cli.run_dreambooth:<module>:14 - ❌ Some DreamBooth components are missing! Please run `autotrain setup` to install it. Ignore this warning if you are not using DreamBooth or running `autotrain setup` already.
> > INFO    Authenticating user...
> > WARNING Parameters not supplied by user and set to default: model_ref, save_total_limit, lr, disable_gradient_checkpointing, gradient_accumulation, train_split, optimizer, token, use_flash_attention_2, dpo_beta, repo_id, push_to_hub, model, trainer, lora_dropout, seed, lora_alpha, evaluation_strategy, save_strategy, model_max_length, weight_decay, add_eos_token, prompt_text_column, text_column, scheduler, project_name, username, valid_split, auto_find_batch_size, max_grad_norm, merge_adapter, data_path, logging_steps, rejected_text_column, batch_size, lora_r, warmup_ratio
> > WARNING Parameters not supplied by user and set to default: save_strategy, weight_decay, max_seq_length, target_column, lr, gradient_accumulation, epochs, save_total_limit, text_column, scheduler, project_name, train_split, optimizer, token, warmup_ratio, username, valid_split, repo_id, auto_find_batch_size, max_grad_norm, log, data_path, push_to_hub, logging_steps, model, batch_size, seed, evaluation_strategy
> > WARNING Parameters not supplied by user and set to default: image_column, save_strategy, weight_decay, target_column, lr, gradient_accumulation, epochs, save_total_limit, scheduler, project_name, train_split, optimizer, token, warmup_ratio, valid_split, repo_id, auto_find_batch_size, max_grad_norm, log, data_path, push_to_hub, logging_steps, model, batch_size, seed, evaluation_strategy
> > WARNING Parameters not supplied by user and set to default: max_seq_length, lr, gradient_accumulation, epochs, save_total_limit, train_split, optimizer, token, repo_id, quantization, push_to_hub, model, peft, lora_dropout, seed, lora_alpha, evaluation_strategy, save_strategy, weight_decay, target_column, text_column, scheduler, project_name, username, valid_split, auto_find_batch_size, max_grad_norm, data_path, logging_steps, batch_size, max_target_length, lora_r, warmup_ratio, target_modules
> > WARNING Parameters not supplied by user and set to default: time_limit, num_trials, id_column, project_name, train_split, token, categorical_imputer, categorical_columns, username, valid_split, numerical_columns, repo_id, numeric_scaler, numerical_imputer, data_path, push_to_hub, model, target_columns, seed, task
> > WARNING Parameters not supplied by user and set to default: num_cycles, adam_beta1, resolution, resume_from_checkpoint, num_class_images, lr_power, train_text_encoder, epochs, bf16, allow_tf32, dataloader_num_workers, rank, prior_preservation, token, pre_compute_text_embeddings, repo_id, logging, prior_generation_precision, push_to_hub, warmup_steps, model, checkpoints_total_limit, validation_epochs, seed, use_8bit_adam, adam_weight_decay, local_rank, tokenizer, center_crop, class_labels_conditioning, xformers, class_prompt, scheduler, text_encoder_use_attention_mask, project_name, xl, scale_lr, checkpointing_steps, adam_beta2, prior_loss_weight, username, max_grad_norm, validation_prompt, adam_epsilon, class_image_path, sample_batch_size, tokenizer_max_length, num_validation_images, revision, image_path, validation_images
> INFO:     Started server process [20544]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://127.0.0.1:7860 (Press CTRL+C to quit)
> INFO:     127.0.0.1:57919 - "GET / HTTP/1.1" 200 OK
> INFO:     127.0.0.1:57919 - "GET /logo.png HTTP/1.1" 304 Not Modified
> > INFO    Task: llm:sft
> INFO:     127.0.0.1:57920 - "GET /params/llm%3Asft HTTP/1.1" 200 OK
> INFO:     127.0.0.1:57921 - "GET /model_choices/llm%3Asft HTTP/1.1" 200 OK
> > INFO    Task: tabular:classification
> INFO:     127.0.0.1:57921 - "GET /params/tabular%3Aclassification HTTP/1.1" 200 OK
> INFO:     127.0.0.1:57920 - "GET /model_choices/tabular%3Aclassification HTTP/1.1" 200 OK
> > INFO    hardware: Local
> > INFO    Running jobs: []
> > INFO    Dataset: 7r3a-niwb-1h6d (tabular_multi_class_classification)
> Train data: [<tempfile.SpooledTemporaryFile object at 0x0000024863F9C640>]
> Valid data: []
> Column mapping: {'id': 'id', 'label': ['target']}
> 
> INFO:     127.0.0.1:57923 - "POST /create_project HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
>     return await self.app(scope, receive, send)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\fastapi\applications.py", line 1106, in __call__
>     await super().__call__(scope, receive, send)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\starlette\applications.py", line 122, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
>     raise exc
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
>     raise exc
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
>     raise e
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
>     await self.app(scope, receive, send)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\starlette\routing.py", line 718, in __call__
>     await route.handle(scope, receive, send)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\starlette\routing.py", line 276, in handle
>     await self.app(scope, receive, send)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\starlette\routing.py", line 66, in app
>     response = await func(request)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\fastapi\routing.py", line 274, in app
>     raw_response = await run_endpoint_function(
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
>     return await dependant.call(**values)
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\autotrain\app.py", line 402, in handle_form
>     dset.prepare()
>   File "C:\Users\migue\AppData\Local\miniconda3\envs\autotrain_env\lib\site-packages\autotrain\dataset.py", line 357, in prepare
>     preprocessor = TabularMultiClassClassificationPreprocessor(
> TypeError: __init__() got an unexpected keyword argument 'local'
> 
```

**Comment by abhishekkrthakur** [comment]
fixed.
