### ISSUE TITLE
[BUG] CLI seems to freeze and terminate with 'PartialState' object has no attribute 'process_index'

### ISSUE THREAD

**Issue by Joao-Pimenta** [huggingface/autotrain-advanced#413]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

```
autotrain llm --train --project_name autotrainMistral_V1 \
--model alexsherstinsky/Mistral-7B-v0.1-sharded --data_path . \
--use-peft --quantization int4 --learning_rate 2e-4 --train_batch_size 1 \
--num_train_epochs 5 --trainer sft --target_modules q_proj,v_proj \
--push_to_hub --repo_id MY_ID
```

### Error Logs

```
[2023-12-19 15:17:23,665] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/vps_ssh/.local/lib/python3.11/site-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
> INFO    Running LLM
> INFO    Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='.', train_split='train', valid_split=None, text_column='text', rejected_text_column='rejected', prompt_text_column='prompt', model='alexsherstinsky/Mistral-7B-v0.1-sharded', model_ref=None, learning_rate=0.0002, num_train_epochs=5, train_batch_size=1, warmup_ratio=0.1, gradient_accumulation_steps=1, optimizer='adamw_torch', scheduler='linear', weight_decay=0.0, max_grad_norm=1.0, seed=42, add_eos_token=False, block_size=-1, peft=True, lora_r=16, lora_alpha=32, lora_dropout=0.05, logging_steps=-1, project_name='autotrainMistral_V1', evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, mixed_precision=None, quantization='int4', push_to_hub=True, model_max_length=1024, repo_id=MY_ID, trainer='sft', target_modules='q_proj,v_proj', merge_adapter=False, backend='default', username=None, use_flash_attention_2=False, log='wandb', disable_gradient_checkpointing=False, dpo_beta=0.1, func=<function run_llm_command_factory at 0x7f3d2e7dad40>)
[2023-12-19 15:17:30,374] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-12-19 15:17:30,374] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/vps_ssh/.local/lib/python3.11/site-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
/home/vps_ssh/.local/lib/python3.11/site-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(








[E socket.cpp:922] [c10d] The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 0).
[E socket.cpp:922] [c10d] The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 0).
--- Logging error in Loguru Handler #1 ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=331264), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'process_input_data', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 43, 'message': 'loading dataset from csv', 'module': '__main__', 'name': '__main__', 'process': (id=20250, name='MainProcess'), 'thread': (id=139920244418368, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 17, 30, 666350, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=329068), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'process_input_data', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 43, 'message': 'loading dataset from csv', 'module': '__main__', 'name': '__main__', 'process': (id=20249, name='MainProcess'), 'thread': (id=139894451672896, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 17, 30, 661530, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 217, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1141, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 217, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 241, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1141, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 168, in _create_c10d_store
    tcp_store = TCPStore(hostname, port, world_size, False, timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 241, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 168, in _create_c10d_store
    tcp_store = TCPStore(hostname, port, world_size, False, timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 0).
TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 0).
--- End of logging error ---
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1801, microseconds=766494), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'process_input_data', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 95, 'message': "Train data: Dataset({\n    features: ['Concept', 'Funny Description Prompt', 'text', 'Unnamed: 3'],\n    num_rows: 508\n})", 'module': '__main__', 'name': '__main__', 'process': (id=20250, name='MainProcess'), 'thread': (id=139920244418368, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 47, 30, 101580, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1801, microseconds=769220), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'process_input_data', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 95, 'message': "Train data: Dataset({\n    features: ['Concept', 'Funny Description Prompt', 'text', 'Unnamed: 3'],\n    num_rows: 508\n})", 'module': '__main__', 'name': '__main__', 'process': (id=20249, name='MainProcess'), 'thread': (id=139894451672896, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 47, 30, 101682, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 360, in is_main_process
    self.process_index == 0 if self.distributed_type != DistributedType.MEGATRON_LM else self.is_last_process
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PartialState' object has no attribute 'process_index'
--- End of logging error ---
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 360, in is_main_process
    self.process_index == 0 if self.distributed_type != DistributedType.MEGATRON_LM else self.is_last_process
    ^^^^^^^^^^^^^^^^^^
--- Logging error in Loguru Handler #1 ---
AttributeError: 'PartialState' object has no attribute 'process_index'
--- End of logging error ---
Record was: {'elapsed': datetime.timedelta(seconds=1801, microseconds=767041), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'process_input_data', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 96, 'message': 'Valid data: None', 'module': '__main__', 'name': '__main__', 'process': (id=20250, name='MainProcess'), 'thread': (id=139920244418368, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 47, 30, 102127, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
--- Logging error in Loguru Handler #1 ---
Traceback (most recent call last):
Record was: {'elapsed': datetime.timedelta(seconds=1801, microseconds=769785), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'process_input_data', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 96, 'message': 'Valid data: None', 'module': '__main__', 'name': '__main__', 'process': (id=20249, name='MainProcess'), 'thread': (id=139894451672896, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 47, 30, 102247, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
Traceback (most recent call last):
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 360, in is_main_process
    self.process_index == 0 if self.distributed_type != DistributedType.MEGATRON_LM else self.is_last_process
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PartialState' object has no attribute 'process_index'
--- End of logging error ---
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 360, in is_main_process
    self.process_index == 0 if self.distributed_type != DistributedType.MEGATRON_LM else self.is_last_process
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PartialState' object has no attribute 'process_index'
--- End of logging error ---
Loading checkpoint shards: 100%|███████████████████████████████████████████████████| 8/8 [00:34<00:00,  4.31s/it]Loading checkpoint shards: 100%|███████████████████████████████████████████████████| 8/8 [00:34<00:00,  4.31s/it]--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1838, microseconds=945016), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'train', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 261, 'message': 'Using block size 1024', 'module': '__main__', 'name': '__main__', 'process': (id=20250, name='MainProcess'), 'thread': (id=139920244418368, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 48, 7, 280102, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
Traceback (most recent call last):
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 360, in is_main_process
    self.process_index == 0 if self.distributed_type != DistributedType.MEGATRON_LM else self.is_last_process
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PartialState' object has no attribute 'process_index'
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1838, microseconds=945540), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'train', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 323, 'message': 'creating trainer', 'module': '__main__', 'name': '__main__', 'process': (id=20250, name='MainProcess'), 'thread': (id=139920244418368, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 48, 7, 280626, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
Traceback (most recent call last):
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 360, in is_main_process
    self.process_index == 0 if self.distributed_type != DistributedType.MEGATRON_LM else self.is_last_process
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PartialState' object has no attribute 'process_index'
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1838, microseconds=956855), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'train', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 261, 'message': 'Using block size 1024', 'module': '__main__', 'name': '__main__', 'process': (id=20249, name='MainProcess'), 'thread': (id=139894451672896, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 48, 7, 289317, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
Traceback (most recent call last):
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 360, in is_main_process
    self.process_index == 0 if self.distributed_type != DistributedType.MEGATRON_LM else self.is_last_process
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PartialState' object has no attribute 'process_index'
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1838, microseconds=957310), 'exception': None, 'extra': {}, 'file': (name='__main__.py', path='/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/trainers/clm/__main__.py'), 'function': 'train', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 323, 'message': 'creating trainer', 'module': '__main__', 'name': '__main__', 'process': (id=20249, name='MainProcess'), 'thread': (id=139894451672896, name='MainThread'), 'time': datetime(2023, 12, 19, 15, 48, 7, 289772, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400), 'EST'))}
Traceback (most recent call last):
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/loguru/_handler.py", line 124, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 37, in <lambda>
    logger.add(sys.stderr, format=log_format, filter=lambda x: should_log(x) and emoji_filter(x))
                                                               ^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/autotrain/logging.py", line 19, in should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vps_ssh/.local/lib/python3.11/site-packages/accelerate/state.py", line 360, in is_main_process
    self.process_index == 0 if self.distributed_type != DistributedType.MEGATRON_LM else self.is_last_process
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'PartialState' object has no attribute 'process_index'
--- End of logging error ---


```

### Additional Information

lspci | grep -i --color 'vga\|3d\|2d'

03:00.0 VGA compatible controller: NVIDIA Corporation TU104GL [Quadro RTX 5000] (rev a1)
06:00.0 VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 30)
82:00.0 VGA compatible controller: NVIDIA Corporation TU104GL [Quadro RTX 5000] (rev a1)

Rocky Linux
The code seems to stop after " UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead. warnings.warn("
For more than 1 hour. Eventually, some errors appear, and another 30 minutes after, the code terminates.

**Comment by abhishekkrthakur** [comment]
seems like something related to the system. have you tried using the docker image?

**Comment by Joao-Pimenta** [comment]
> seems like something related to the system. have you tried using the docker image?

Just tried it, but I'm using it in a Rocky Linux server, and got some issues with the NVIDIA drivers required for the docker container. I'm currently just using the UI in Hugging Face and paying for their hardware, but would love to find a way to run it in my server
