### ISSUE TITLE
[BUG] Failed to Save Images

### ISSUE THREAD

**Issue by expelledboy** [huggingface/autotrain-advanced#421]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### CLI Command

```
!autotrain dreambooth \
--model ${MODEL_NAME} \
--project-name ${PROJECT_NAME} \
--image-path ./images/ \
--prompt "${PROMPT}" \
--resolution ${RESOLUTION} \
--batch-size ${BATCH_SIZE} \
--num-steps ${NUM_STEPS} \
--gradient-accumulation ${GRADIENT_ACCUMULATION} \
--lr ${LEARNING_RATE} \
$( [[ "$USE_FP16" == "True" ]] && echo "--fp16" ) \
$( [[ "$USE_XFORMERS" == "True" ]] && echo "--xformers" ) \
$( [[ "$TRAIN_TEXT_ENCODER" == "True" ]] && echo "--train-text-encoder" ) \
$( [[ "$USE_8BIT_ADAM" == "True" ]] && echo "--use-8bit-adam" ) \
$( [[ "$GRADIENT_CHECKPOINTING" == "True" ]] && echo "--gradient-checkpointing" ) \
$( [[ "$PUSH_TO_HUB" == "True" ]] && echo "--push-to-hub --token ${HF_TOKEN} --repo-id ${REPO_ID}" )
```

### UI Screenshots & Parameters

![image](https://github.com/huggingface/autotrain-advanced/assets/102334/01c022d0-efcf-4a97-ae5f-0b68c4f3c0da)

### Error Logs

```
> INFO    Saving concept images
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 48, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_dreambooth.py", line 483, in run
    params = dreambooth_munge_data(params, local=self.args.backend.startswith("local"))
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/utils.py", line 145, in dreambooth_munge_data
    params.data_path = dset.prepare()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/dataset.py", line 80, in prepare
    return preprocessor.prepare()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/preprocessor/dreambooth.py", line 80, in prepare
    self._save_concept_images(_file)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/preprocessor/dreambooth.py", line 63, in _save_concept_images
    _file = file.file.read()
AttributeError: '_io.BytesIO' object has no attribute 'file'. Did you mean: 'fileno'?
```

### Additional Information

I can not seem to get the google colab notebook to load my images. I have changed the format, size, name. All without success.

**Comment by adamfils** [comment]
Same here

**Comment by abhishekkrthakur** [comment]
fixed. please use version 0.6.66 or above.

**Comment by abhishekkrthakur** [comment]
can one of you please confirm if it works now so we can close the issue? :)

**Comment by expelledboy** [comment]
I am running the model now. I has gotten past this issue. Thank you!
