### ISSUE TITLE
[BUG]Fine tuning meta-llama/Llama-2-7b-chat-hf fails at the last stage  

### ISSUE THREAD

**Issue by AhilanPonnusamy** [huggingface/autotrain-advanced#427]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### CLI Command

Using AutoTrain_LLM.ipynb and the key parameters used are 

- Model Name :  meta-llama/Llama-2-7b-chat-hf 
- train.csv uploaded under data folder with "text" column
- num_epocs 3

### UI Screenshots & Parameters

![error](https://github.com/huggingface/autotrain-advanced/assets/24754948/6bcdab5a-0341-4d95-adc1-88fc987106f5)

### Error Logs

❌ ERROR  | 2023-12-21 01:57:44 | autotrain.trainers.common:wrapper:86 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 446, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1990, in _inner_training_loop
    self.control = self.callback_handler.on_train_end(args, self.state, self.control)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer_callback.py", line 373, in on_train_end
    return self.call_event("on_train_end", args, state, control)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer_callback.py", line 414, in call_event
    result = getattr(callback, event)(
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/callbacks.py", line 36, in on_train_end
    adapters_weights = torch.load(best_model_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'xbc-finetuning/checkpoint-18/adapter_model.bin'

❌ ERROR  | 2023-12-21 01:57:44 | autotrain.trainers.common:wrapper:87 - [Errno 2] No such file or directory: 'xbc-finetuning/checkpoint-18/adapter_model.bin'
100% 18/18 [07:23<00:00, 24.65s/it]

### Additional Information

Tried other llama2 chat models e.g., NousResearch/Llama-2-7b-chat-hf and got the same error

**Comment by abhishekkrthakur** [comment]
please paste cli parameters.

**Comment by AhilanPonnusamy** [comment]
!autotrain llm \
--train \
--model meta-llama/Llama-2-7b-chat-hf \
--project-name xbc-finetuning \
--data-path data/ \
--text-column text \
--lr 2e-4 \
--batch-size 1 \
--epochs 3 \
--block-size 1024 \
--warmup-ratio 0.1 \
--lora-r 16 \
--lora-alpha 32 \
--lora-dropout 0.05 \
--weight-decay 0.01 \
--gradient-accumulation 4 \
--quantization int4 \
--mixed-precision fp16 \
--peft"  --push-to-hub --token ${HF_TOKEN} --repo-id AhilanPonnusamy/xbc-finetuning-chat-output

**Comment by abhishekkrthakur** [comment]
fixed. please update via pip

**Comment by AhilanPonnusamy** [comment]
Perfect.. It works like a charm.. Thank you Abhishek
