### ISSUE TITLE
[BUG] KeyError: 'text' in llm train in Pip Install (multiple versions)

### ISSUE THREAD

**Issue by sfc-gh-jsummer** [huggingface/autotrain-advanced#441]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain llm --train --project-name $PROJECT_NAME --model $MODEL_CARD --data-path stage/ --text_column text --use-peft --quantization int4 --lr 1e-4 --train-batch-size 4 --epochs 3 --trainer sft --token $HF_TOKEN --merge_adapter

### Error Logs

❌ ERROR  | 2023-12-24 23:33:40 | autotrain.trainers.common:wrapper:90 - train has failed due to an exception: Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/autotrain/trainers/common.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/autotrain/trainers/clm/__main__.py", line 469, in train
    trainer.train()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 280, in train
    output = super().train(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/transformers/trainer.py", line 1821, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/accelerate/data_loader.py", line 639, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/accelerate/data_loader.py", line 601, in _fetch_batches
    batches.append(next(iterator))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/trl/trainer/utils.py", line 565, in __iter__
    buffer.append(self.formatting_func(next(iterator)))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/trl/trainer/utils.py", line 541, in <lambda>
    self.formatting_func = lambda x: x[dataset_text_field]
KeyError: 'text'

### Additional Information

Key Error produced in pip installed autotrain-advanced from source (0.6.80.dev0) and 0.6.79. 

Note that I've tried the stable version (0.6.48) noted on HF website but that produces below error with autotrain setup, autotrain --version, and autotrain llm:

```
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/autotrain/cli/autotrain.py", line 6, in <module>
    from .run_dreambooth import RunAutoTrainDreamboothCommand
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/autotrain/cli/run_dreambooth.py", line 5, in <module>
    from autotrain import logger
ImportError: cannot import name 'logger' from 'autotrain' (/opt/conda/envs/rapids/lib/python3.10/site-packages/autotrain/__init__.py)
```

**Comment by abhishekkrthakur** [comment]
the keyerror is due to the fact that you dont have a column named `text` in your train.csv. or train.csv is not inside stage/ folder.

**Comment by sfc-gh-jsummer** [comment]
I didn't realize I had removed the file in the mounted stage. Thanks.
