### ISSUE TITLE
AutoTrain died with <Signals.SIGKILL:9>

### ISSUE THREAD

**Issue by HGPai** [huggingface/autotrain-advanced#456]
I'm trying to fine tune a Falcon-7B-instruct model using the LLM finetuning colab script. 
It returns this error: 

Downloading shards: 100% 2/2 [01:41<00:00, 51.00s/it]
Loading checkpoint shards:   0% 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'autotrain.trainers.clm', '--training_config', 'autotrain-LLM/training_params.json']' died with <Signals.SIGKILL: 9>.

How to solve this?

**Comment by abhishekkrthakur** [comment]
gpu or ram went out of memory. bigger machine will fix this issue

**Comment by HGPai** [comment]
Yep that worked! thanks @abhishekkrthakur
