### ISSUE TITLE
[BUG] dependencies are not installed: libGL, torchvision

### ISSUE THREAD

**Issue by mrticker** [huggingface/autotrain-advanced#466]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Other cloud providers

### Interface Used

CLI

### Error Logs

RuntimeError: Failed to import diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl because of the following error (look up to see its traceback):
libGL.so.1: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/opt/conda/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/opt/conda/lib/python3.9/site-packages/autotrain/cli/autotrain.py", line 6, in <module>
    from .run_dreambooth import RunAutoTrainDreamboothCommand
  File "/opt/conda/lib/python3.9/site-packages/autotrain/cli/run_dreambooth.py", line 10, in <module>
    from autotrain.trainers.dreambooth.utils import VALID_IMAGE_EXTENSIONS, XL_MODELS
  File "/opt/conda/lib/python3.9/site-packages/autotrain/trainers/dreambooth/utils.py", line 15, in <module>
    from autotrain.trainers.dreambooth.datasets import PromptDataset
  File "/opt/conda/lib/python3.9/site-packages/autotrain/trainers/dreambooth/datasets.py", line 7, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'

### Additional Information

apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
pip install torchvision

**Comment by abhishekkrthakur** [comment]
you need to install torchvision & torch. if its saying its not found, its not installed or you are not using correct environment.
you can also use huggingface/autotrain-advanced:latest docker image to avoid dependencies problems.

**Comment by mrticker** [comment]
I opened this issue in hope that the requirements would be added to requirements.txt or something, you know.
