### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'[BUG]

### ISSUE THREAD

**Issue by simonushie** [huggingface/autotrain-advanced#501]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### Error Logs

> INFO    Namespace(version=False, revision=None, tokenizer=None, image_path='images/', class_image_path=None, prompt='photo of VM', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, resolution=1024, center_crop=None, train_text_encoder=None, sample_batch_size=4, num_steps=500, checkpointing_steps=100000, resume_from_checkpoint=None, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=None, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=None, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, train=None, deploy=None, inference=None, username=None, backend='local-cli', token=None, repo_id=None, push_to_hub=None, model='stabilityai/stable-diffusion-xl-base-1.0', project_name='linkedin_pfp_project', seed=42, epochs=1, gradient_accumulation=4, disable_gradient_checkpointing=None, lr=0.0001, log='none', data_path=None, train_split='train', valid_split=None, batch_size=30, func=<function run_dreambooth_command_factory at 0x79251681edd0>)
> INFO    Running DreamBooth Training
> WARNING Parameters supplied but not used: log, backend, valid_split, deploy, train_split, data_path, inference, train, func, version
> INFO    Dataset: linkedin_pfp_project (dreambooth)

> INFO    Saving concept images
> INFO    images/IMG_20240120_180714.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_175752.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_175908.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_175954.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_175716.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_170036.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_175717.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_180028.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_175659.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_170011.jpg
> INFO    Starting local training...
> INFO    {"model":"stabilityai/stable-diffusion-xl-base-1.0","revision":null,"tokenizer":null,"image_path":"linkedin_pfp_project/autotrain-data","class_image_path":null,"prompt":"photo of VM","class_prompt":null,"num_class_images":100,"class_labels_conditioning":null,"prior_preservation":false,"prior_loss_weight":1.0,"project_name":"linkedin_pfp_project","seed":42,"resolution":1024,"center_crop":false,"train_text_encoder":false,"batch_size":30,"sample_batch_size":4,"epochs":1,"num_steps":500,"checkpointing_steps":100000,"resume_from_checkpoint":null,"gradient_accumulation":4,"disable_gradient_checkpointing":false,"lr":0.0001,"scale_lr":false,"scheduler":"constant","warmup_steps":0,"num_cycles":1,"lr_power":1.0,"dataloader_num_workers":0,"use_8bit_adam":false,"adam_beta1":0.9,"adam_beta2":0.999,"adam_weight_decay":0.01,"adam_epsilon":1e-8,"max_grad_norm":1.0,"allow_tf32":false,"prior_generation_precision":null,"local_rank":-1,"xformers":false,"pre_compute_text_embeddings":false,"tokenizer_max_length":null,"text_encoder_use_attention_mask":false,"rank":4,"xl":true,"fp16":true,"bf16":false,"token":null,"repo_id":null,"push_to_hub":false,"username":null,"validation_prompt":null,"num_validation_images":4,"validation_epochs":50,"checkpoints_total_limit":null,"validation_images":null,"logging":false}
> INFO    ['python', '-m', 'autotrain.trainers.dreambooth', '--training_config', 'linkedin_pfp_project/training_params.json']
tokenizer/tokenizer_config.json: 100% 737/737 [00:00<00:00, 3.03MB/s]
tokenizer/vocab.json: 100% 1.06M/1.06M [00:00<00:00, 18.5MB/s]
tokenizer/merges.txt: 100% 525k/525k [00:00<00:00, 42.7MB/s]
tokenizer/special_tokens_map.json: 100% 472/472 [00:00<00:00, 2.92MB/s]
tokenizer_2/tokenizer_config.json: 100% 725/725 [00:00<00:00, 4.62MB/s]
tokenizer_2/special_tokens_map.json: 100% 460/460 [00:00<00:00, 2.82MB/s]
text_encoder/config.json: 100% 565/565 [00:00<00:00, 3.58MB/s]
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
text_encoder_2/config.json: 100% 575/575 [00:00<00:00, 3.55MB/s]
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
model.safetensors: 100% 492M/492M [00:02<00:00, 174MB/s]
model.safetensors: 100% 2.78G/2.78G [00:29<00:00, 95.1MB/s]
vae/config.json: 100% 642/642 [00:00<00:00, 3.20MB/s]
diffusion_pytorch_model.safetensors: 100% 335M/335M [00:01<00:00, 184MB/s]
unet/config.json: 100% 1.68k/1.68k [00:00<00:00, 10.8MB/s]
diffusion_pytorch_model.safetensors: 100% 10.3G/10.3G [01:50<00:00, 92.7MB/s]
{'dropout', 'attention_type'} was not found in config. Values will be initialized to default values.
scheduler/scheduler_config.json: 100% 479/479 [00:00<00:00, 2.47MB/s]
{'thresholding', 'variance_type', 'dynamic_thresholding_ratio', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
🚀 INFO   | 2024-02-11 08:02:06 | autotrain.trainers.dreambooth.utils:enable_gradient_checkpointing:298 - Enabling gradient checkpointing.
🚀 INFO   | 2024-02-11 08:02:06 | autotrain.trainers.dreambooth.trainer:compute_text_embeddings:140 - Computing text embeddings for prompt: photo of VM
❌ ERROR  | 2024-02-11 08:02:07 | autotrain.trainers.common:wrapper:91 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 297, in train
    trainer = Trainer(
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 50, in __init__
    self._setup_xl()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 165, in _setup_xl
    ) = self.compute_text_embeddings(self.config.prompt)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 142, in compute_text_embeddings
    prompt_embeds, pooled_prompt_embeds = utils.encode_prompt_xl(self.text_encoders, self.tokenizers, prompt)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/utils.py", line 130, in encode_prompt_xl
    prompt_embeds = text_encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 798, in forward
    return self.text_model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 703, in forward
    encoder_outputs = self.encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 630, in forward
    layer_outputs = encoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 371, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/normalization.py", line 196, in forward
    return F.layer_norm(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2543, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

❌ ERROR  | 2024-02-11 08:02:07 | autotrain.trainers.common:wrapper:92 - "LayerNormKernelImpl" not implemented for 'Half'

### Additional Information

i want to know please if a GPU switch will truly solve this issue, thanks

**Comment by simonushie** [comment]
> ### Prerequisites
> * [x]  I have read the [documentation](https://hf.co/docs/autotrain).
> * [x]  I have checked other issues for similar problems.
> 
> ### Backend
> Colab
> 
> ### Interface Used
> UI
> 
> ### CLI Command
> _No response_
> 
> ### UI Screenshots & Parameters
> _No response_
> 
> ### Error Logs
> > INFO    Namespace(version=False, revision=None, tokenizer=None, image_path='images/', class_image_path=None, prompt='photo of VM', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, resolution=1024, center_crop=None, train_text_encoder=None, sample_batch_size=4, num_steps=500, checkpointing_steps=100000, resume_from_checkpoint=None, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=None, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=None, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, train=None, deploy=None, inference=None, username=None, backend='local-cli', token=None, repo_id=None, push_to_hub=None, model='stabilityai/stable-diffusion-xl-base-1.0', project_name='linkedin_pfp_project', seed=42, epochs=1, gradient_accumulation=4, disable_gradient_checkpointing=None, lr=0.0001, log='none', data_path=None, train_split='train', valid_split=None, batch_size=30, func=<function run_dreambooth_command_factory at 0x79251681edd0>)
> > INFO    Running DreamBooth Training
> > WARNING Parameters supplied but not used: log, backend, valid_split, deploy, train_split, data_path, inference, train, func, version
> > INFO    Dataset: linkedin_pfp_project (dreambooth)
> 
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_180714.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_175752.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_175908.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_175954.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_175716.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_170036.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_175717.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_180028.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_175659.jpg
> > INFO    Saving concept images
> > INFO    images/IMG_20240120_170011.jpg
> > INFO    Starting local training...
> > INFO    {"model":"stabilityai/stable-diffusion-xl-base-1.0","revision":null,"tokenizer":null,"image_path":"linkedin_pfp_project/autotrain-data","class_image_path":null,"prompt":"photo of VM","class_prompt":null,"num_class_images":100,"class_labels_conditioning":null,"prior_preservation":false,"prior_loss_weight":1.0,"project_name":"linkedin_pfp_project","seed":42,"resolution":1024,"center_crop":false,"train_text_encoder":false,"batch_size":30,"sample_batch_size":4,"epochs":1,"num_steps":500,"checkpointing_steps":100000,"resume_from_checkpoint":null,"gradient_accumulation":4,"disable_gradient_checkpointing":false,"lr":0.0001,"scale_lr":false,"scheduler":"constant","warmup_steps":0,"num_cycles":1,"lr_power":1.0,"dataloader_num_workers":0,"use_8bit_adam":false,"adam_beta1":0.9,"adam_beta2":0.999,"adam_weight_decay":0.01,"adam_epsilon":1e-8,"max_grad_norm":1.0,"allow_tf32":false,"prior_generation_precision":null,"local_rank":-1,"xformers":false,"pre_compute_text_embeddings":false,"tokenizer_max_length":null,"text_encoder_use_attention_mask":false,"rank":4,"xl":true,"fp16":true,"bf16":false,"token":null,"repo_id":null,"push_to_hub":false,"username":null,"validation_prompt":null,"num_validation_images":4,"validation_epochs":50,"checkpoints_total_limit":null,"validation_images":null,"logging":false}
> > INFO    ['python', '-m', 'autotrain.trainers.dreambooth', '--training_config', 'linkedin_pfp_project/training_params.json']
> > tokenizer/tokenizer_config.json: 100% 737/737 [00:00<00:00, 3.03MB/s]
> > tokenizer/vocab.json: 100% 1.06M/1.06M [00:00<00:00, 18.5MB/s]
> > tokenizer/merges.txt: 100% 525k/525k [00:00<00:00, 42.7MB/s]
> > tokenizer/special_tokens_map.json: 100% 472/472 [00:00<00:00, 2.92MB/s]
> > tokenizer_2/tokenizer_config.json: 100% 725/725 [00:00<00:00, 4.62MB/s]
> > tokenizer_2/special_tokens_map.json: 100% 460/460 [00:00<00:00, 2.82MB/s]
> > text_encoder/config.json: 100% 565/565 [00:00<00:00, 3.58MB/s]
> > You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
> > text_encoder_2/config.json: 100% 575/575 [00:00<00:00, 3.55MB/s]
> > You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
> > model.safetensors: 100% 492M/492M [00:02<00:00, 174MB/s]
> > model.safetensors: 100% 2.78G/2.78G [00:29<00:00, 95.1MB/s]
> > vae/config.json: 100% 642/642 [00:00<00:00, 3.20MB/s]
> > diffusion_pytorch_model.safetensors: 100% 335M/335M [00:01<00:00, 184MB/s]
> > unet/config.json: 100% 1.68k/1.68k [00:00<00:00, 10.8MB/s]
> > diffusion_pytorch_model.safetensors: 100% 10.3G/10.3G [01:50<00:00, 92.7MB/s]
> > {'dropout', 'attention_type'} was not found in config. Values will be initialized to default values.
> > scheduler/scheduler_config.json: 100% 479/479 [00:00<00:00, 2.47MB/s]
> > {'thresholding', 'variance_type', 'dynamic_thresholding_ratio', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
> > 🚀 INFO   | 2024-02-11 08:02:06 | autotrain.trainers.dreambooth.utils:enable_gradient_checkpointing:298 - Enabling gradient checkpointing.
> > 🚀 INFO   | 2024-02-11 08:02:06 | autotrain.trainers.dreambooth.trainer:compute_text_embeddings:140 - Computing text embeddings for prompt: photo of VM
> > ❌ ERROR  | 2024-02-11 08:02:07 | autotrain.trainers.common:wrapper:91 - train has failed due to an exception: Traceback (most recent call last):
> > File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 88, in wrapper
> > return func(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/**main**.py", line 297, in train
> > trainer = Trainer(
> > File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 50, in **init**
> > self._setup_xl()
> > File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 165, in _setup_xl
> > ) = self.compute_text_embeddings(self.config.prompt)
> > File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 142, in compute_text_embeddings
> > prompt_embeds, pooled_prompt_embeds = utils.encode_prompt_xl(self.text_encoders, self.tokenizers, prompt)
> > File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/utils.py", line 130, in encode_prompt_xl
> > prompt_embeds = text_encoder(
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 798, in forward
> > return self.text_model(
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 703, in forward
> > encoder_outputs = self.encoder(
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 630, in forward
> > layer_outputs = encoder_layer(
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 371, in forward
> > hidden_states = self.layer_norm1(hidden_states)
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/normalization.py", line 196, in forward
> > return F.layer_norm(
> > File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2543, in layer_norm
> > return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
> > RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
> 
> ❌ ERROR | 2024-02-11 08:02:07 | autotrain.trainers.common:wrapper:92 - "LayerNormKernelImpl" not implemented for 'Half'
> 
> ### Additional Information
> i want to know please if a GPU switch will truly solve this issue, thanks

![image](https://github.com/huggingface/autotrain-advanced/assets/43451941/4484f8fa-76f7-438b-8980-ed08d75e9b79)

change from cpu to GPU solved this, click runtimes>runtime type>T4 GPU
