### ISSUE TITLE
[BUG] Module 'bitsandbytes.nn' has no attribute 'Linear4bit'

### ISSUE THREAD

**Issue by Cohejh** [huggingface/autotrain-advanced#504]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

I ran `autotrain llm --train --project-name PROJECTNAME --model MODELNAME --token TOKEN --data-path DATASET --text_column text --use-peft  --quantization int4 --lr 2e-4 --train-batch-size 2 --epochs 5 --trainer sft --model_max_length 2048 --push-to-hub --repo-id REPOID --block_size 2048`

### Error Logs

```
❌ ERROR  | 2024-02-12 17:21:18 | autotrain.trainers.common:wrapper:91 - train has failed due to an exception: Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\autotrain\trainers\common.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\autotrain\trainers\clm\__main__.py", line 186, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Program Files\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Program Files\Python310\lib\site-packages\transformers\modeling_utils.py", line 3651, in from_pretrained
    model = replace_with_bnb_linear(
  File "C:\Program Files\Python310\lib\site-packages\transformers\integrations\bitsandbytes.py", line 235, in replace_with_bnb_linear
    model, has_been_replaced = _replace_with_bnb_linear(
  File "C:\Program Files\Python310\lib\site-packages\transformers\integrations\bitsandbytes.py", line 196, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
  File "C:\Program Files\Python310\lib\site-packages\transformers\integrations\bitsandbytes.py", line 196, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
  File "C:\Program Files\Python310\lib\site-packages\transformers\integrations\bitsandbytes.py", line 196, in _replace_with_bnb_linear
    _, has_been_replaced = _replace_with_bnb_linear(
  [Previous line repeated 1 more time]
  File "C:\Program Files\Python310\lib\site-packages\transformers\integrations\bitsandbytes.py", line 182, in _replace_with_bnb_linear
    model._modules[name] = bnb.nn.Linear4bit(
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?

❌ ERROR  | 2024-02-12 17:21:18 | autotrain.trainers.common:wrapper:92 - module 'bitsandbytes.nn' has no attribute 'Linear4bit'
```

**Comment by abhishekkrthakur** [comment]
quantization not supported for windows

**Comment by Cohejh** [comment]
> quantization not supported for windows

Ok, thank you very much
