### ISSUE TITLE
[BUG]Getting Error: RepoID Must contain AlphaNumeric Values when Running on Google Colab

### ISSUE THREAD

**Issue by SyntaxPratyush** [huggingface/autotrain-advanced#535]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### UI Screenshots & Parameters

![image](https://github.com/huggingface/autotrain-advanced/assets/157193581/a7881433-8094-4e33-acc0-392824fd585f)

### Error Logs

```
❌ ERROR  | 2024-03-07 14:24:35 | autotrain.trainers.common:wrapper:91 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 128, in train
    train_data, valid_data = process_input_data(config)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 71, in process_input_data
    train_data = load_dataset(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1815, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1512, in dataset_module_factory
    raise e1 from None
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1479, in dataset_module_factory
    raise e
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1453, in dataset_module_factory
    dataset_info = hf_api.dataset_info(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'data/'.

❌ ERROR  | 2024-03-07 14:24:35 | autotrain.trainers.common:wrapper:92 - Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'data/'.

```

**Comment by abhishekkrthakur** [comment]
please add the full command as printed

**Comment by SyntaxPratyush** [comment]
> please add the full command as printed

I do not understand

**Comment by abhishekkrthakur** [comment]
i dont see all the arguments passed to the autotrain command. when you run the command, it logs a dictionary. remove your token and post the full command please

**Comment by SyntaxPratyush** [comment]
> i dont see all the arguments passed to the autotrain command. when you run the command, it logs a dictionary. remove your token and post the full command please

here is link to my notebook - https://colab.research.google.com/drive/19LCuZgUr9grca-TJrXHavm4O3lY3Ka02?usp=sharing

**Comment by SyntaxPratyush** [comment]
> i dont see all the arguments passed to the autotrain command. when you run the command, it logs a dictionary. remove your token and post the full command please

and here is the code - 
![image](https://github.com/huggingface/autotrain-advanced/assets/157193581/2d2f80ce-6cf1-44b4-967d-6da69f5d4bc6)

**Comment by abhishekkrthakur** [comment]
it seems like train.csv is missing inside `data/`

**Comment by SyntaxPratyush** [comment]
> it seems like train.csv is missing inside `data/`

how do i add that (i apologize i am an absolute beginner to this)

**Comment by SyntaxPratyush** [comment]
more specifically where do i add it?(i already have the file)

**Comment by AntouanK** [comment]
I have the same issue.
What was the solution?
