### ISSUE TITLE
Sequence packing issue 

### ISSUE THREAD

**Issue by treeoflovely** [huggingface/autotrain-advanced#567]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Hugging Face Space/Endpoints

### Interface Used

UI

### UI Screenshots & Parameters

<img width="735" alt="Screenshot 2024-04-02 110820" src="https://github.com/huggingface/autotrain-advanced/assets/125883982/ae17b670-5334-49d4-aa12-858cc4b5e563">
{
  "block_size": 1024,
  "model_max_length": 2048,
  "padding": "right",
  "use_flash_attention_2": false,
  "disable_gradient_checkpointing": false,
  "logging_steps": -1,
  "evaluation_strategy": "epoch",
  "save_total_limit": 1,
  "save_strategy": "no",
  "auto_find_batch_size": true,
  "mixed_precision": "fp16",
  "lr": 0.00003,
  "epochs": 3,
  "batch_size": 2,
  "warmup_ratio": 0.1,
  "gradient_accumulation": 4,
  "optimizer": "adamw_torch",
  "scheduler": "linear",
  "weight_decay": 0,
  "max_grad_norm": 1,
  "seed": 42,
  "chat_template": "none",
  "quantization": "int4",
  "target_modules": "all-linear",
  "merge_adapter": true,
  "peft": true,
  "lora_r": 64,
  "lora_alpha": 128,
  "lora_dropout": 0.05
}

### Error Logs

❌ ERROR  | 2024-04-02 14:53:24 | autotrain.trainers.common:wrapper:115 - train has failed due to an exception: Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1676, in _prepare_split_single
    for key, record in generator:
  File "/app/env/lib/python3.10/site-packages/datasets/packaged_modules/generator/generator.py", line 30, in _generate_examples
    for idx, ex in enumerate(self.config.generator(**gen_kwargs)):
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 517, in data_generator
    yield from constant_length_iterator
  File "/app/env/lib/python3.10/site-packages/trl/trainer/utils.py", line 457, in __iter__
    buffer.append(self.formatting_func(next(iterator)))
  File "/app/env/lib/python3.10/site-packages/trl/trainer/utils.py", line 434, in <lambda>
    self.formatting_func = lambda x: x[dataset_text_field]
KeyError: 'text'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 520, in _prepare_packed_dataloader
    packed_dataset = Dataset.from_generator(
  File "/app/env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1072, in from_generator
    ).read()
  File "/app/env/lib/python3.10/site-packages/datasets/io/generator.py", line 47, in read
    self.builder.download_and_prepare(
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1717, in _download_and_prepare
    super()._download_and_prepare(
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1555, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1712, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/src/autotrain/trainers/common.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/app/src/autotrain/trainers/clm/__main__.py", line 480, in train
    trainer = SFTTrainer(
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 282, in __init__
    train_dataset = self._prepare_dataset(
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 419, in _prepare_dataset
    return self._prepare_packed_dataloader(
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 524, in _prepare_packed_dataloader
    raise ValueError(
ValueError: Error occurred while packing the dataset. Make sure that your dataset has enough samples to at least yield one packed sequence.
❌ ERROR  | 2024-04-02 14:53:24 | autotrain.trainers.common:wrapper:116 - Error occurred while packing the dataset. Make sure that your dataset has enough samples to at least yield one packed sequence.

### Additional Information

Tried this with both uploaded datasets as well as datasets hosted on the hub. It doesn't seem to be model or size related as I have attempted with everything from 7b to 70b and Mistral as well as Llama.

**Comment by abhishekkrthakur** [comment]
it seems like your dataset has very short sentences? if thats the case, reduce blocksize to quite a small value like 32 or even 16

**Comment by treeoflovely** [comment]
I bumped it down to 32 (anything less would truncate the vast majority) and it still throws the same error. 

🚀 INFO   | 2024-04-02 16:28:52 | __main__:train:332 - model dtype: torch.float16
🚀 INFO   | 2024-04-02 16:28:52 | __main__:train:340 - preparing peft model...
🚀 INFO   | 2024-04-02 16:29:04 | __main__:train:391 - Using block size 32
🚀 INFO   | 2024-04-02 16:29:04 | __main__:train:453 - creating trainer
Generating train split: 0 examples [00:00, ? examples/s]
Generating train split: 0 examples [00:00, ? examples/s]
❌ ERROR  | 2024-04-02 16:29:05 | autotrain.trainers.common:wrapper:115 - train has failed due to an exception: Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1676, in _prepare_split_single
    for key, record in generator:
  File "/app/env/lib/python3.10/site-packages/datasets/packaged_modules/generator/generator.py", line 30, in _generate_examples
    for idx, ex in enumerate(self.config.generator(**gen_kwargs)):
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 517, in data_generator
    yield from constant_length_iterator
  File "/app/env/lib/python3.10/site-packages/trl/trainer/utils.py", line 457, in __iter__
    buffer.append(self.formatting_func(next(iterator)))
  File "/app/env/lib/python3.10/site-packages/trl/trainer/utils.py", line 434, in <lambda>
    self.formatting_func = lambda x: x[dataset_text_field]
KeyError: 'text'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 520, in _prepare_packed_dataloader
    packed_dataset = Dataset.from_generator(
  File "/app/env/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1072, in from_generator
    ).read()
  File "/app/env/lib/python3.10/site-packages/datasets/io/generator.py", line 47, in read
    self.builder.download_and_prepare(
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1717, in _download_and_prepare
    super()._download_and_prepare(
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1555, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/app/env/lib/python3.10/site-packages/datasets/builder.py", line 1712, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/src/autotrain/trainers/common.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/app/src/autotrain/trainers/clm/__main__.py", line 480, in train
    trainer = SFTTrainer(
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 282, in __init__
    train_dataset = self._prepare_dataset(
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 419, in _prepare_dataset
    return self._prepare_packed_dataloader(
  File "/app/env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 524, in _prepare_packed_dataloader
    raise ValueError(
ValueError: Error occurred while packing the dataset. Make sure that your dataset has enough samples to at least yield one packed sequence.
❌ ERROR  | 2024-04-02 16:29:05 | autotrain.trainers.common:wrapper:116 - Error occurred while packing the dataset. Make sure that your dataset has enough samples to at least yield one packed sequence.

**Comment by abhishekkrthakur** [comment]
is it possible for you to share the dataset?

**Comment by treeoflovely** [comment]
Not possible. I can  try to recreate the error with one I can.
