### ISSUE TITLE
Getting error while  initiate local servercannot import name 'get_full_repo_name' from 'huggingface_hub'

### ISSUE THREAD

**Issue by x-technik** [huggingface/autotrain-advanced#569]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### Error Logs

(train) erdag@corsair540:~$ autotrain app --port 8080 --host 127.0.0.1
Traceback (most recent call last):
  File "/home/erdag/miniconda3/envs/train/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/autotrain/__init__.py", line 30, in <module>
    from autotrain.logging import custom_logger as logger  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/autotrain/logging.py", line 3, in <module>
    from accelerate.state import PartialState
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/accelerate/utils/__init__.py", line 182, in <module>
    from .megatron_lm import (
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/accelerate/utils/megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/transformers/utils/__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub' (/home/erdag/miniconda3/envs/train/lib/python3.11/site-packages/huggingface_hub/__init__.py)

**Comment by abhishekkrthakur** [comment]
is this still an issue?

**Comment by Error504TimeOut** [comment]
it is :/

**Comment by abhishekkrthakur** [comment]
unfortunately, i dont see this issue. what is the version of autotrain you are using? how did you install it?

**Comment by Error504TimeOut** [comment]
for me, i exactly followed the steps in the readme. i use conda

**Comment by abhishekkrthakur** [comment]
i just tried a clean install in a brand new conda installation and it seems to have worked completely fine for me.
maybe something bad happened during installation and some packages were not installed? 
can you try `pip install -U autotrain-advanced` ?

**Comment by Error504TimeOut** [comment]
i did, still the same.

**Comment by abhishekkrthakur** [comment]
is it a new conda env? if not, you might be have different versions of dependencies? 

try:

`pip install peft==0.10.0 trl==0.8.1 transformers==4.39.3 accelerate==0.29.1 huggingface_hub==0.22.2`

and then `autotrain app`

**Comment by Error504TimeOut** [comment]
nope. reports that all requirements are satisfied and leaves it at that. output still the same

**Comment by abhishekkrthakur** [comment]
does `conda install chardet` fix it?

**Comment by Error504TimeOut** [comment]
for some reason, it does. for me at least

**Comment by abhishekkrthakur** [comment]
¯\_(ツ)_/¯

I will close this issue for now :)
