### ISSUE TITLE
Cannot open the Auto train site anymore

### ISSUE THREAD

**Issue by vecterror** [huggingface/autotrain-advanced#572]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### Error Logs

Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 6, in <module>
    from .run_dreambooth import RunAutoTrainDreamboothCommand
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_dreambooth.py", line 10, in <module>
    from autotrain.trainers.dreambooth.utils import VALID_IMAGE_EXTENSIONS, XL_MODELS
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/utils.py", line 10, in <module>
    list_models(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
TypeError: HfApi.list_models() got an unexpected keyword argument 'task'

**Comment by abhishekkrthakur** [comment]
fixed. please update.
