### ISSUE TITLE
[BUG] autotrain app doesn't work even with HF_TOKEN env var set

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [huggingface/autotrain-advanced#578]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain app

### UI Screenshots & Parameters

I have set HF_TOKEN env variable locally (verified by doing `echo $HF_TOKEN`)

### Error Logs

```
(base) ➜  ~ autotrain app                                    [24/04/10| 2:34AM]
> ERROR   HF_TOKEN not set
Traceback (most recent call last):
  File "/Users/dhruvanand/miniforge3/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/Users/dhruvanand/miniforge3/lib/python3.10/site-packages/autotrain/cli/autotrain.py", line 50, in main
    command.run()
  File "/Users/dhruvanand/miniforge3/lib/python3.10/site-packages/autotrain/cli/run_app.py", line 51, in run
    from autotrain.app import app
  File "/Users/dhruvanand/miniforge3/lib/python3.10/site-packages/autotrain/app.py", line 38, in <module>
    raise ValueError("HF_TOKEN environment variable is not set")
ValueError: HF_TOKEN environment variable is not set
```

### Additional Information

I read through https://github.com/huggingface/autotrain-advanced/issues/279

**Comment by abhishekkrthakur** [comment]
it should be `export HF_TOKEN=your_token`

**Comment by dhruv-anand-aintech** [comment]
I mentioned I've already set it. Verified by doing echo $HF_TOKEN

**Comment by abhishekkrthakur** [comment]
the app is not seeing the token. can you try 
`HF_TOKEN=..... autotrain app`
