### ISSUE TITLE
[BUG] "--project-name" argument can not be set as a directory

### ISSUE THREAD

**Issue by tamastarjanyi** [huggingface/autotrain-advanced#582]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

AT_PROJECT_NAME="test"
AT_DATA_PATH="/data/${AT_PROJECT_NAME}"
AT_MODEL_NAME="meta-llama/Llama-2-13b-hf"
AT_TRAINER="sft" # default, sft, reward, dpo
AT_LORA_R=32
AT_EPOCHS=10
AT_BATCH_SIZE=4

autotrain llm \
    --project-name "/models/{AT_PROJECT_NAME}" \
    --model ${AT_MODEL_NAME} \
    --data-path ${AT_DATA_PATH} \
    --text-column "text" \
    --trainer ${AT_TRAINER} \
    --use-peft \
    --model_max_length 4096 \
    --block_size 4096 \
    --lr 2e-4 \
    --lora_r ${AT_LORA_R} \
    --logging_steps 10 \
    --save_total_limit 3 \
    --save_strategy "epoch" \
    --batch-size=${AT_BATCH_SIZE} \
    --epochs ${AT_EPOCHS} \
    --train

### Error Logs

Traceback (most recent call last):
  File "/opt/conda/envs/autotrain/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/autotrain/lib/python3.10/site-packages/autotrain/cli/autotrain.py", line 50, in main
    command.run()
  File "/opt/conda/envs/autotrain/lib/python3.10/site-packages/autotrain/cli/run_llm.py", line 331, in run
    params = LLMTrainingParams(**vars(self.args))
  File "/opt/conda/envs/autotrain/lib/python3.10/site-packages/autotrain/trainers/common.py", line 157, in __init__
    raise ValueError("project_name must be alphanumeric but can contain hyphens")
ValueError: project_name must be alphanumeric but can contain hyphens

### Additional Information

This code part is

**Comment by abhishekkrthakur** [comment]
its not a bug. its by design.

**Comment by tamastarjanyi** [comment]
autotrain llm --help
...
  --project-name PROJECT_NAME
                        Output directory or repo id
...

**Comment by abhishekkrthakur** [comment]
its a directory in the local folder where you run the command. in your case, you can run the command in `/models/` folder and --project-name will be `AT_PROJECT_NAME`
