### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hemanth** [huggingface/autotrain-advanced#602]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

```
autotrain llm \
--train \
--model microsoft/Phi-3-mini-4k-instruct \
--data-path timdettmers/openassistant-guanaco \
--lr 2e-4 \
--batch-size 2 \
--epochs 1 \
--trainer sft \
--peft \
--project-name phi3guanaco \
--username gnumanth \
--push-to-hub \
--token hf_...
```

### UI Screenshots & Parameters

<img width="624" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/18315/00fa87d3-5dac-449b-923a-b46e892feef3">

### Error Logs

Well, this might not be direct issue with `auto-train` seeing the above error on HF and `TypeError: BFloat16 is not supported on MPS` on `M1` even after a `model.to("cpu")`

**Comment by abhishekkrthakur** [comment]
its not an autotrain issue. you can try the code in readme and use it locally or deploy using inferencce endpoints. you can send this issue to: website@hf.co as it looks like problem with api inference.

**Comment by hemanth** [comment]
Thank you @abhishekkrthakur but `TypeError: BFloat16 is not supported on MPS` can be fixed via `autotrain` flags? 

https://huggingface.co/gnumanth/phi3guanaco is the model I have published using the scripts suggested [here](https://huggingface.co/blog/abhishek/phi3-finetune-macbook)

**Comment by abhishekkrthakur** [comment]
could you please add full logs of error? and code to reproduce it? :)

**Comment by hemanth** [comment]
Indeed! 

```python

from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = "gnumanth/phi3guanaco"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype='auto'
).eval()

model.to("cpu")

# Prompt content: "hi"
messages = [
    {"role": "user", "content": "hi"}
]

input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
output_ids = model.generate(input_ids.to('cuda'))
response = tokenizer.decode(output_ids[0][input_ids.shape[1]:], skip_special_tokens=True)

# Model response: "Hello! How can I assist you today?"
print(response)
```

Stack trace:

```sh
Traceback (most recent call last):
  File "/private/tmp/k.py", line 7, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/Users/hemanth/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
  File "/Users/hemanth/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/Users/hemanth/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3926, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/Users/hemanth/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/modeling_utils.py", line 805, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/Users/hemanth/.pyenv/versions/3.10.12/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 384, in set_module_tensor_to_device
    new_value = value.to(device)
TypeError: BFloat16 is not supported on MPS
```

**Comment by abhishekkrthakur** [comment]
torch dtype = torch.float16 should work no? ill give it a try myself.

**Comment by hemanth** [comment]
@abhishekkrthakur I thought so to, maybe I am missing something obvious?

**Comment by hemanth** [comment]
@abhishekkrthakur any luck on your end?
