### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by StefanIsMe** [huggingface/autotrain-advanced#618]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain app --port 8080 --host 127.0.0.1

### Error Logs

D:\projects\testfinetune>autotrain app --port 8080 --host 127.0.0.1
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Programs\Python\Python312\Scripts\autotrain.exe\__main__.py", line 7, in <module>
  File "D:\Programs\Python\Python312\Lib\site-packages\autotrain\cli\autotrain.py", line 62, in main
    command.run()
  File "D:\Programs\Python\Python312\Lib\site-packages\autotrain\cli\run_app.py", line 100, in run
    preexec_fn=os.setsid,
               ^^^^^^^^^
AttributeError: module 'os' has no attribute 'setsid'. Did you mean: 'getpid'?

**Comment by abhishekkrthakur** [comment]
please use docker image or WSL if you are using windows.
