### ISSUE TITLE
[BUG] autotrain app fails on start

### ISSUE THREAD

**Issue by dejankocic** [huggingface/autotrain-advanced#631]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain app --port 8082 --host 127.0.0.1

### Error Logs

(autotrain) PS C:\Users\XXX> autotrain app --port 8082 --host 127.0.0.1
Traceback (most recent call last):
  File "C:\Python\Python39-11\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python39-11\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\venv\python3911venv\Scripts\autotrain.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\XXX\venv\python3911venv\lib\site-packages\autotrain\cli\autotrain.py", line 62, in main
    command.run()
  File "C:\Users\XXX\venv\python3911venv\lib\site-packages\autotrain\cli\run_app.py", line 100, in run
    preexec_fn=os.setsid,
AttributeError: module 'os' has no attribute 'setsid'

**Comment by abhishekkrthakur** [comment]
windows support is unfortunately not there. you can try using WSL or docker image.

**Comment by dejankocic** [comment]
Thx. Let me try with a Linux box.

**Comment by candre23** [comment]
> windows support is unfortunately not there. you can try using WSL or docker image.

Sadly, WSL refuses to allow cuda for enterprise cards.  Those of us using old datacenter silicon on windows can only run natively.

As this seems to be all python, it should(?) be platform-independent, no?

**Comment by abhishekkrthakur** [comment]
@candre23 you can use it if you disable quantization
