### ISSUE TITLE
[BUG] Autotrain fails due to missing metadata.jsonl, after removing my metadata.jsonl file.

### ISSUE THREAD

**Issue by rileybolen** [huggingface/autotrain-advanced#653]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Hugging Face Space/Endpoints

### Interface Used

UI

### UI Screenshots & Parameters

![Screenshot 2024-05-22 at 8 01 39 AM](https://github.com/huggingface/autotrain-advanced/assets/24947668/446c2a8b-c905-4468-8454-d53d2e651e6e)

### Error Logs

Removed file: /app/.cache/autotrain/863f2b2b-5c1e-40df-9c6c-bec8a6c71a6d/metadata.jsonl
INFO:     10.16.41.118:54118 - "POST /ui/create_project HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/app/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/app/env/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/env/lib/python3.10/site-packages/autotrain/app/ui_routes.py", line 349, in handle_form
    data_path = dset.prepare()
  File "/app/env/lib/python3.10/site-packages/autotrain/dataset.py", line 223, in prepare
    preprocessor = ObjectDetectionPreprocessor(
  File "<string>", line 11, in __init__
  File "/app/env/lib/python3.10/site-packages/autotrain/preprocessor/vision.py", line 184, in __post_init__
    raise ValueError(f"{self.train_data} should contain a metadata.jsonl file.")
ValueError: /app/.cache/autotrain/863f2b2b-5c1e-40df-9c6c-bec8a6c71a6d should contain a metadata.jsonl file.

### Additional Information

I am trying to use autotrain to fine tune an image detection model, and the training fails to start. It throws a 500 error, saying that the metadata.jsonl file is missing, but right before this it gives a message saying that it removed my metadata.jsonl file. I have formatted my data acording to [these docs](https://huggingface.co/docs/autotrain/object_detection), although there seem to be some contradictions in the instructions on this page.

**Comment by abhishekkrthakur** [comment]
thanks for reporting this.
fixed in version 0.7.104 and above.
