### ISSUE TITLE
[BUG]Tabular Classification Error

### ISSUE THREAD

**Issue by uisikdag** [huggingface/autotrain-advanced#663]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

UI

### UI Screenshots & Parameters

![image](https://github.com/huggingface/autotrain-advanced/assets/6618891/69c000a5-3d1a-4709-a57d-91d8d07e0ce4)

### Error Logs

FileNotFoundError: [Errno 2] No such file or directory: 'python'

raise child_exception_type(errno_num, err_msg, err_filename)

File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child

self._execute_child(args, executable, preexec_fn, close_fds,

File "/usr/lib/python3.10/subprocess.py", line 971, in __init__

process = subprocess.Popen(cmd, env=env)

File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 55, in run_training

training_pid = run_training(params, task_id, local=True, wait=self.wait)

File "/usr/local/lib/python3.10/dist-packages/autotrain/backends/local.py", line 11, in create

return runner.create()

File "/usr/local/lib/python3.10/dist-packages/autotrain/project.py", line 63, in create

job_id = project.create()

File "/usr/local/lib/python3.10/dist-packages/autotrain/app/ui_routes.py", line 624, in handle_form

return await dependant.call(**values)

File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function

raw_response = await run_endpoint_function(

File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 278, in app

response = await func(request)

File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app

await app(scope, receive, sender)

File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app

raise exc

File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app

await wrap_app_handling_exceptions(app, request)(scope, receive, send)

File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app

await self.app(scope, receive, send)

File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle

await route.handle(scope, receive, send)

File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app

await self.middleware_stack(scope, receive, send)

File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__

await app(scope, receive, sender)

File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app

raise exc

File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app

await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__

await self.app(scope, receive, _send)

File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__

raise exc

File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__

await self.middleware_stack(scope, receive, send)

File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__

await super().__call__(scope, receive, send)

File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__

return await self.app(scope, receive, send)

File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__

result = await app( # type: ignore[func-returns-value]

File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi

Traceback (most recent call last):

ERROR: Exception in ASGI application

INFO | 2024-06-01 01:36:05 | autotrain.commands:launch_command:387 - {'data_path': 'autotrain-c41wh-jf5zc/autotrain-data', 'model': 'xgboost', 'username': 'uisikdag', 'seed': 42, 'train_split': 'train', 'valid_split': 'validation', 'project_name': 'autotrain-c41wh-jf5zc', 'token': '*****', 'push_to_hub': True, 'id_column': 'autotrain_id', 'target_columns': ['autotrain_label'], 'categorical_columns': None, 'numerical_columns': None, 'task': 'classification', 'num_trials': 10, 'time_limit': 600, 'categorical_imputer': 'most_frequent', 'numerical_imputer': 'median', 'numeric_scaler': 'robust'}

INFO | 2024-06-01 01:36:05 | autotrain.commands:launch_command:386 - ['python', '-m', 'autotrain.trainers.tabular', '--training_config', 'autotrain-c41wh-jf5zc/training_params.json']

INFO | 2024-06-01 01:36:05 | autotrain.backends.local:create:8 - Starting local training...

Saving the dataset (1/1 shards): 100%|██████████| 2/2 [00:00<00:00, 1136.82 examples/s]

Saving the dataset (1/1 shards): 100%|██████████| 2/2 [00:00<00:00, 1190.72 examples/s]

Saving the dataset (0/1 shards): 0%| | 0/2 [00:00<?, ? examples/s]

Saving the dataset (1/1 shards): 100%|██████████| 8/8 [00:00<00:00, 4346.43 examples/s]

Saving the dataset (1/1 shards): 100%|██████████| 8/8 [00:00<00:00, 4562.13 examples/s]

Saving the dataset (0/1 shards): 0%| | 0/8 [00:00<?, ? examples/s]

INFO | 2024-06-01 01:36:05 | autotrain.app.ui_routes:handle_form:590 - Column mapping: {'id': 'id', 'label': ['target']}

INFO | 2024-06-01 01:36:05 | autotrain.app.ui_routes:handle_form:589 - Task: tabular_multi_class_classification

INFO | 2024-06-01 01:36:05 | autotrain.app.ui_routes:handle_form:483 - hardware: local-ui

### Additional Information

The dataset
id,category1,category2,feature1,target
1,A,X,0.3373961604172684,1
2,B,Z,0.6481718720511972,0
3,A,Y,0.36824153984054797,1
4,B,Z,0.9571551589530464,1
5,B,Z,0.14035078041264515,1
6,C,X,0.8700872583584364,1
7,A,Y,0.4736080452737105,0
8,C,Y,0.8009107519796442,1
9,A,Y,0.5204774795512048,0
10,A,Y,0.6788795301189603,0

**Comment by uisikdag** [comment]
requires python 3.11 to solve the problem

**Comment by abhishekkrthakur** [comment]
please share problem so i can solve it
