### ISSUE TITLE
[BUG] ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub'

### ISSUE THREAD

**Issue by ksingh-scogo** [huggingface/autotrain-advanced#673]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Other cloud providers

### Interface Used

CLI

### CLI Command

$ conda create -n autotrain python=3.10
$ conda activate autotrain
$ pip install autotrain-advanced
$ conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
$ conda install -c "nvidia/label/cuda-12.1.0" cuda-nvcc
$ conda install xformers -c xformers
$ python -m nltk.downloader punkt
$ pip install flash-attn --no-build-isolation # if you want to use flash-attn
$ pip install deepspeed # if you want to use deepspeed

### Error Logs

```
autotrain app --host 127.0.0.1 --port 8000
Traceback (most recent call last):
  File "/mnt/miniconda3/envs/autotrain/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/autotrain/__init__.py", line 30, in <module>
    from autotrain.logging import Logger
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/autotrain/logging.py", line 4, in <module>
    from accelerate.state import PartialState
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 192, in <module>
    from .megatron_lm import (
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/accelerate/utils/megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/transformers/utils/__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub' (/mnt/miniconda3/envs/autotrain/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

**Comment by ksingh-scogo** [comment]
@abhishekkrthakur  i read your comment on https://github.com/huggingface/autotrain-advanced/issues/569#issuecomment-2043343860 

Then i did `conda install chardet` in the autotrain conda env to fix this issue 

```
autotrain app --host 127.0.0.1 --port 8000

Your installed package `nvidia-ml-py` is corrupted. Skip patch functions `nvmlDeviceGet{Compute,Graphics,MPSCompute}RunningProcesses`. You may get incorrect or incomplete results. Please consider reinstall package `nvidia-ml-py` via `pip3 install --force-reinstall nvidia-ml-py nvitop`.
Your installed package `nvidia-ml-py` is corrupted. Skip patch functions `nvmlDeviceGetMemoryInfo`. You may get incorrect or incomplete results. Please consider reinstall package `nvidia-ml-py` via `pip3 install --force-reinstall nvidia-ml-py nvitop`.
INFO     | 2024-06-10 04:58:37 | autotrain.app.ui_routes:<module>:30 - Starting AutoTrain...

INFO     | 2024-06-10 04:58:49 | autotrain.app.ui_routes:<module>:287 - AutoTrain started successfully
INFO     | 2024-06-10 04:58:49 | autotrain.app.app:<module>:13 - Starting AutoTrain...
INFO     | 2024-06-10 04:58:49 | autotrain.app.app:<module>:23 - AutoTrain version: 0.7.118
INFO     | 2024-06-10 04:58:49 | autotrain.app.app:<module>:24 - AutoTrain started successfully
INFO:     Started server process [30609]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

Reporting it again , if we need to document in the installation instructions ? thoughts ?

**Comment by abhishekkrthakur** [comment]
this shouldnt be an issue. ill include it in FAQs
