### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by fre2mansur** [huggingface/autotrain-advanced#694]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

conda create -n autotrain python=3.10
conda activate autotrain
pip install autotrain-advanced
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
conda install -c "nvidia/label/cuda-12.1.0" cuda-nvcc
Once done, you can start the application using:

autotrain app --port 8080 --host 127.0.0.1

### Error Logs

(autotrain) dell@dell-Latitude-E7470:~/projects/ai$ autotrain app --port 8080 --host 127.0.0.1
Traceback (most recent call last):
  File "/home/dell/.pyenv/versions/3.9.7/bin/autotrain", line 5, in <module>
    from autotrain.cli.autotrain import main
  File "/home/dell/.pyenv/versions/3.9.7/lib/python3.9/site-packages/autotrain/__init__.py", line 28, in <module>
    import torch._dynamo
  File "/home/dell/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/__init__.py", line 17, in <module>
    import ctypes
  File "/home/dell/.pyenv/versions/3.9.7/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

### Additional Information

I haven't clone this repo. it's not needed right?

**Comment by abhishekkrthakur** [comment]
does this work: https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul ?
