### ISSUE TITLE
[BUG] Unable to auto train paligemma 

### ISSUE THREAD

**Issue by jupiterlearningdevops** [huggingface/autotrain-advanced#715]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

UI

### UI Screenshots & Parameters

![image](https://github.com/user-attachments/assets/4d9dd8ac-fdb8-4ccf-903c-755bdfaa36d7)

![image](https://github.com/user-attachments/assets/c7b7441f-c28a-4ef0-9d6e-154120b502b4)

### Error Logs

INFO | 2024-07-27 21:51:50 | autotrain.app.utils:kill_process_by_pid:52 - Sent SIGTERM to process with PID 713

INFO | 2024-07-27 21:51:50 | autotrain.app.utils:get_running_jobs:26 - Killing PID: 713

0%| | 0/3 [00:00<?, ?it/s]

ERROR | 2024-07-27 21:51:49 | autotrain.trainers.common:wrapper:121 - 'autotrain_prompt'

KeyError: 'autotrain_prompt'

prompts = ["answer " + example[config.prompt_text_column] for example in examples]

File "/app/env/lib/python3.10/site-packages/autotrain/trainers/vlm/train_vlm_generic.py", line 13, in <listcomp>

prompts = ["answer " + example[config.prompt_text_column] for example in examples]

File "/app/env/lib/python3.10/site-packages/autotrain/trainers/vlm/train_vlm_generic.py", line 13, in collate_fn

return self.collate_fn(data)

File "/app/env/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch

data = self._dataset_fetcher.fetch(index) # may raise StopIteration

File "/app/env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data

data = self._next_data()

File "/app/env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__

current_batch = next(dataloader_iter)

File "/app/env/lib/python3.10/site-packages/accelerate/data_loader.py", line 454, in __iter__

for step, inputs in enumerate(epoch_iterator):

File "/app/env/lib/python3.10/site-packages/transformers/trainer.py", line 2236, in _inner_training_loop

return inner_training_loop(

File "/app/env/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train

trainer.train()

File "/app/env/lib/python3.10/site-packages/autotrain/trainers/vlm/train_vlm_generic.py", line 97, in train

train_generic(config)

File "/app/env/lib/python3.10/site-packages/autotrain/trainers/vlm/__main__.py", line 27, in train

return func(*args, **kwargs)

File "/app/env/lib/python3.10/site-packages/autotrain/trainers/common.py", line 117, in wrapper

0%| | 0/3 [00:00<?, ?it/s]ERROR | 2024-07-27 21:51:49 | autotrain.trainers.common:wrapper:120 - train has failed due to an exception: Traceback (most recent call last):

INFO | 2024-07-27 21:51:48 | autotrain.trainers.common:on_train_begin:230 - Starting to train...

warnings.warn(

/app/env/lib/python3.10/site-packages/transformers/models/paligemma/configuration_paligemma.py:137: FutureWarning: The `vocab_size` attribute is deprecated and will be removed in v4.44, Please use `text_config.vocab_size` instead.

[93m [WARNING] [0m using untested triton version (2.3.0), only 1.0.0 is known to be compatible

[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3

[93m [WARNING] [0m NVIDIA Inference is only supported on Ampere and newer architectures

[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH

[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.

[93m [WARNING] [0m async_io: please install the libaio-dev package with apt

[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.

[2024-07-27 21:51:48,616] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)

INFO | 2024-07-27 21:51:48 | autotrain.trainers.vlm.train_vlm_generic:train:80 - creating trainer

INFO | 2024-07-27 21:51:47 | autotrain.trainers.vlm.utils:get_model:232 - preparing peft model...

INFO | 2024-07-27 21:51:47 | autotrain.trainers.vlm.utils:get_model:229 - model dtype: torch.float16

### Additional Information

Tried to train with a test dataset using the UI.
Followed the exact steps mentioned here: https://huggingface.co/blog/abhishek/paligemma-finetuning-autotrain
But ended up getting the error.

The zip file that was used for testing the finetuning  : 
[train.zip](https://github.com/user-attachments/files/16401543/train.zip)

**Comment by abhishekkrthakur** [comment]
it seems like your column mappings are incorrect? can you share first few lines from metadata.jsonl?
