### ISSUE TITLE
[BUG] Pair Score Sentence Transformer Training is not supported on Google Collab

### ISSUE THREAD

**Issue by unclemusclez** [huggingface/autotrain-advanced#746]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### CLI Command

Link from `README.md` https://colab.research.google.com/github/huggingface/autotrain-advanced/blob/main/colabs/AutoTrain.ipynb

I am attempting Pair Score Sentence Transformer Training.

### Error Logs

```
Training is starting... Please wait!
INFO     | 2024-08-31 01:57:16 | autotrain.cli.autotrain:main:60 - Using AutoTrain configuration: config.yml
Traceback (most recent call last):
File "/usr/local/bin/autotrain", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 61, in main
cp = AutoTrainConfigParser(args.config)
File "<string>", line 4, in __init__
File "/usr/local/lib/python3.10/dist-packages/autotrain/parser.py", line 142, in __post_init__
raise ValueError(f"Task `{self.task}` is not supported")
ValueError: Task `st` is not supported
An error occurred while starting training!
Error: Training failed with exit code: 1
```

**Comment by abhishekkrthakur** [comment]
fixed in v0.8.14 and above.
