### ISSUE TITLE
[BUG]i get this error everytime

### ISSUE THREAD

**Issue by unbreakablepunjab** [huggingface/autotrain-advanced#808]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### Error Logs

Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/main.py", line 5, in
from diffusers.utils import convert_all_state_dict_to_peft, convert_state_dict_to_kohya
File "/usr/local/lib/python3.10/dist-packages/diffusers/init.py", line 5, in
from .utils import (
File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/init.py", line 38, in
from .dynamic_modules_utils import get_class_from_dynamic_module
File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in
from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/init.py)

**Comment by abhishekkrthakur** [comment]
this seems like an issue where older version of diffusers doesnt work with newer huggingface_hub library. the training part needs to be updated with diffusers version. ill take a look. in the meantime you can just use an older version of autotrain
